/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.asirisupermarket.view;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.util.Calendar;
import java.util.GregorianCalendar;
import lk.ijse.asirisupermarket.subpanels.ManageOrder;
import lk.ijse.asirisupermarketsystem.panel.ProductPanel;
import lk.ijse.asirisupermarketsystem.panel.ManageCustomers;
import lk.ijse.asirisupermarketsystem.panel.ManageEmployee1;
import lk.ijse.asirisupermarketsystem.panel.ManageSupplier;
import lk.ijse.asirisupermarketsystem.panel.ManageReport;
import lk.ijse.asirisupermarketsystem.panel.OrdersPanel;
import lk.ijse.asirisupermarketsystem.panel.logopanel;

/**
 *
 * @author Hafees
 */
public class MainWindow extends javax.swing.JFrame {

    private int timeRun;

    /**
     * Creates new form DashBoard
     */
    public MainWindow() {
        initComponents();
        setExtendedState(MainWindow.MAXIMIZED_BOTH);
        int timeRun = 0;
        setLocationRelativeTo(null);
        getPanelSize();
        currentime();
        MouseEvent evt = null;
        home_lblMouseClicked( evt);
        
        home_lbl.setDisplayedMnemonic(KeyEvent.VK_F1);
         invoice_lbl.setDisplayedMnemonic(KeyEvent.VK_F3);
       home_lbl.setToolTipText("Home Screen");
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel1 = new javax.swing.JPanel();
        mainpanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        home_lbl = new javax.swing.JLabel();
        product_lbl = new javax.swing.JLabel();
        invoice_lbl = new javax.swing.JLabel();
        report_lbl = new javax.swing.JLabel();
        customer_lbl = new javax.swing.JLabel();
        supplier_lbl = new javax.swing.JLabel();
        lblEmployee = new javax.swing.JLabel();
        mainpanel3 = new javax.swing.JPanel();
        lbltime = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnminimize = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);

        mainPanel1.setBackground(new java.awt.Color(0, 0, 204));
        mainPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        mainPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        mainPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));

        mainpanel2.setBackground(new java.awt.Color(0, 0, 153));
        mainpanel2.setMaximumSize(new java.awt.Dimension(1266, 668));
        mainpanel2.setMinimumSize(new java.awt.Dimension(1266, 668));
        mainpanel2.setPreferredSize(new java.awt.Dimension(1266, 668));

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        home_lbl.setDisplayedMnemonic(1);
        home_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        home_lbl.setForeground(new java.awt.Color(255, 255, 255));
        home_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/asirisupermarket/images/home-64.png"))); // NOI18N
        home_lbl.setText("    Home");
        home_lbl.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        home_lbl.setIconTextGap(0);
        home_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_lblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                home_lblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                home_lblMouseExited(evt);
            }
        });
        home_lbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                home_lblKeyPressed(evt);
            }
        });

        product_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        product_lbl.setForeground(new java.awt.Color(255, 255, 255));
        product_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/asirisupermarket/images/product64b.png"))); // NOI18N
        product_lbl.setText("   Product");
        product_lbl.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        product_lbl.setIconTextGap(0);
        product_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                product_lblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                product_lblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                product_lblMouseExited(evt);
            }
        });

        invoice_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        invoice_lbl.setForeground(new java.awt.Color(255, 255, 255));
        invoice_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/asirisupermarket/images/invoice3.png"))); // NOI18N
        invoice_lbl.setText("    Invoice");
        invoice_lbl.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        invoice_lbl.setIconTextGap(0);
        invoice_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invoice_lblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                invoice_lblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                invoice_lblMouseExited(evt);
            }
        });

        report_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        report_lbl.setForeground(new java.awt.Color(255, 255, 255));
        report_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/asirisupermarket/images/report.png"))); // NOI18N
        report_lbl.setText("    Report");
        report_lbl.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        report_lbl.setIconTextGap(0);
        report_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                report_lblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                report_lblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                report_lblMouseExited(evt);
            }
        });

        customer_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        customer_lbl.setForeground(new java.awt.Color(255, 255, 255));
        customer_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/asirisupermarket/images/customer.png"))); // NOI18N
        customer_lbl.setText("    Customer");
        customer_lbl.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        customer_lbl.setIconTextGap(0);
        customer_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customer_lblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                customer_lblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                customer_lblMouseExited(evt);
            }
        });

        supplier_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        supplier_lbl.setForeground(new java.awt.Color(255, 255, 255));
        supplier_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/asirisupermarket/images/supplier.png"))); // NOI18N
        supplier_lbl.setText("    Supplier");
        supplier_lbl.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        supplier_lbl.setIconTextGap(0);
        supplier_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplier_lblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supplier_lblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supplier_lblMouseExited(evt);
            }
        });

        lblEmployee.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEmployee.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/asirisupermarket/images/settings.png"))); // NOI18N
        lblEmployee.setText("      Employee");
        lblEmployee.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblEmployee.setIconTextGap(0);
        lblEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEmployeeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEmployeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEmployeeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mainpanel3Layout = new javax.swing.GroupLayout(mainpanel3);
        mainpanel3.setLayout(mainpanel3Layout);
        mainpanel3Layout.setHorizontalGroup(
            mainpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1087, Short.MAX_VALUE)
        );
        mainpanel3Layout.setVerticalGroup(
            mainpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(home_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(invoice_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(product_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customer_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(supplier_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(report_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainpanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(home_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(invoice_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(product_lbl)
                .addGap(27, 27, 27)
                .addComponent(customer_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(supplier_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(report_lbl)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainpanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lbltime.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbltime.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 204));
        jLabel1.setText("         Asiri Super Market");

        javax.swing.GroupLayout mainpanel2Layout = new javax.swing.GroupLayout(mainpanel2);
        mainpanel2.setLayout(mainpanel2Layout);
        mainpanel2Layout.setHorizontalGroup(
            mainpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainpanel2Layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(lbltime, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainpanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainpanel2Layout.setVerticalGroup(
            mainpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpanel2Layout.createSequentialGroup()
                .addGroup(mainpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(lbltime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnminimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/asirisupermarket/images/minimize.png"))); // NOI18N
        btnminimize.setBorderPainted(false);
        btnminimize.setContentAreaFilled(false);
        btnminimize.setFocusPainted(false);
        btnminimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnminimizeActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/asirisupermarket/images/Cancel_48px_1.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanel1Layout = new javax.swing.GroupLayout(mainPanel1);
        mainPanel1.setLayout(mainPanel1Layout);
        mainPanel1Layout.setHorizontalGroup(
            mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(mainpanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnminimize, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
        mainPanel1Layout.setVerticalGroup(
            mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btnminimize, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mainpanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void invoice_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoice_lblMouseClicked
        OrdersPanel mn=new OrdersPanel();
        mn.setSize(mainpanel3.getSize());
        mainpanel3.removeAll();
        mainpanel3.add(mn);
        mainpanel3.revalidate();
        mainpanel3.repaint();

    }//GEN-LAST:event_invoice_lblMouseClicked

    private void lblEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmployeeMouseClicked
        ManageEmployee1 mn = new ManageEmployee1();
        mn.setSize(mainpanel3.getSize());
        mainpanel3.removeAll();
        mainpanel3.add(mn);
        mainpanel3.revalidate();
        mainpanel3.repaint();
    }//GEN-LAST:event_lblEmployeeMouseClicked

    private void report_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_report_lblMouseClicked
        
        ManageReport mn=new ManageReport();
        mn.setSize(mainpanel3.getSize());
        mainpanel3.removeAll();
        mainpanel3.add(mn);
        mainpanel3.revalidate();
        mainpanel3.repaint();
    }//GEN-LAST:event_report_lblMouseClicked

    private void supplier_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplier_lblMouseClicked
        ManageSupplier mn = new ManageSupplier();
        mn.setSize(mainpanel3.getSize());
        mainpanel3.removeAll();
        mainpanel3.add(mn);
        mainpanel3.revalidate();
        mainpanel3.repaint();
    }//GEN-LAST:event_supplier_lblMouseClicked

    private void product_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product_lblMouseClicked
        ProductPanel mn = new ProductPanel();
        mn.setSize(mainpanel3.getSize());
        mainpanel3.removeAll();
        mainpanel3.add(mn);
        mainpanel3.revalidate();
        mainpanel3.repaint();
    }//GEN-LAST:event_product_lblMouseClicked

    private void customer_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customer_lblMouseClicked
        ManageCustomers mn = new ManageCustomers();
        mn.setSize(mainpanel3.getSize());
        mainpanel3.removeAll();
        mainpanel3.add(mn);
        mainpanel3.revalidate();
        mainpanel3.repaint();
    }//GEN-LAST:event_customer_lblMouseClicked

    private void home_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_lblMouseClicked
         logopanel mn = new logopanel();
        mn.setSize(mainpanel3.getSize());
        mainpanel3.removeAll();
        mainpanel3.add(mn);
        mainpanel3.revalidate();
        mainpanel3.repaint();
    }//GEN-LAST:event_home_lblMouseClicked

    private void home_lblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_lblMouseEntered
        home_lbl.setBackground(Color.GREEN);
        home_lbl.setOpaque(true);
    }//GEN-LAST:event_home_lblMouseEntered

    private void home_lblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_lblMouseExited
       home_lbl.setBackground(null);
      // home_lbl.setOpaque(false);
      // home_lbl.repaint();
    }//GEN-LAST:event_home_lblMouseExited

    private void invoice_lblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoice_lblMouseEntered
         invoice_lbl.setBackground(Color.GREEN);
        invoice_lbl.setOpaque(true);
    }//GEN-LAST:event_invoice_lblMouseEntered

    private void invoice_lblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoice_lblMouseExited
        invoice_lbl.setBackground(null);
    }//GEN-LAST:event_invoice_lblMouseExited

    private void product_lblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product_lblMouseEntered
        product_lbl.setBackground(Color.GREEN);
        product_lbl.setOpaque(true);
    }//GEN-LAST:event_product_lblMouseEntered

    private void product_lblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product_lblMouseExited
         product_lbl.setBackground(null);
    }//GEN-LAST:event_product_lblMouseExited

    private void customer_lblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customer_lblMouseEntered
   customer_lbl.setBackground(Color.GREEN);
  customer_lbl.setOpaque(true);
  
    }//GEN-LAST:event_customer_lblMouseEntered

    private void customer_lblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customer_lblMouseExited
       customer_lbl.setBackground(null);
    }//GEN-LAST:event_customer_lblMouseExited

    private void supplier_lblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplier_lblMouseEntered
   supplier_lbl.setBackground(Color.GREEN);
  supplier_lbl.setOpaque(true);
 
    }//GEN-LAST:event_supplier_lblMouseEntered

    private void supplier_lblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplier_lblMouseExited
         supplier_lbl.setBackground(null);
    }//GEN-LAST:event_supplier_lblMouseExited

    private void lblEmployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmployeeMouseEntered
        lblEmployee.setBackground(Color.GREEN);
        lblEmployee.setOpaque(true);
        
    }//GEN-LAST:event_lblEmployeeMouseEntered

    private void lblEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmployeeMouseExited
         lblEmployee.setBackground(null);
    }//GEN-LAST:event_lblEmployeeMouseExited

    private void report_lblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_report_lblMouseEntered
             report_lbl.setBackground(Color.GREEN);
             report_lbl.setOpaque(true);
            
    }//GEN-LAST:event_report_lblMouseEntered

    private void report_lblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_report_lblMouseExited
           report_lbl.setBackground(null);
    }//GEN-LAST:event_report_lblMouseExited

    private void home_lblKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_home_lblKeyPressed
        ManageOrder mn=new ManageOrder();
        mn.setVisible(true);
    }//GEN-LAST:event_home_lblKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnminimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnminimizeActionPerformed
        this.setState(MainWindow.ICONIFIED);
    }//GEN-LAST:event_btnminimizeActionPerformed

    public void getPanelSize() {
        
        //int h=mainpanel3.getSize().height;
        // int w=mainpanel3.getSize().width;
        // System.out.println(w+","+h);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnminimize;
    private javax.swing.JLabel customer_lbl;
    public static javax.swing.JLabel home_lbl;
    private javax.swing.JLabel invoice_lbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEmployee;
    private javax.swing.JLabel lbltime;
    private javax.swing.JPanel mainPanel1;
    private javax.swing.JPanel mainpanel2;
    private javax.swing.JPanel mainpanel3;
    private javax.swing.JLabel product_lbl;
    private javax.swing.JLabel report_lbl;
    private javax.swing.JLabel supplier_lbl;
    // End of variables declaration//GEN-END:variables

    private void currentime() {
        new Thread() {
            public void run() {
                while (timeRun == 0) {
                    Calendar cal = new GregorianCalendar();
                    int hour = cal.get(Calendar.HOUR);
                    int min = cal.get(Calendar.MINUTE);
                    int sec = cal.get(Calendar.SECOND);
                    int AM_PM = cal.get(Calendar.AM_PM);

                    String day_night = "";
                    if (AM_PM == 1) {
                        day_night = "PM";
                    } else {
                        day_night = "AM";
                    }
                    String time = hour + ":" + min + ":" + sec + ":" + day_night;

                    lbltime.setText(time);

                }
            }
        }.start();
    }
}
