/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.asirisupermarket.subpanels;

import java.math.BigDecimal;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.asirisupermarket.controller.ManageBatchController;
import lk.ijse.asirisupermarket.controller.ManageCategoryController;
import lk.ijse.asirisupermarket.controller.ManageGRNController;

import lk.ijse.asirisupermarket.core.dto.BatchDTO;
import lk.ijse.asirisupermarket.core.dto.GrnDTO;
import lk.ijse.asirisupermarket.idgenerater.IdGenerater;


/**
 *
 * @author Hafees
 */
public class ManageBatch extends javax.swing.JPanel {

    /**
     * Creates new form ManagerCategory
     */
    public ManageBatch() {
        initComponents();
         loadAllBatches();
         setId();
         loadSystemDate();
         loadallgrnids();
        // DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); 
//         Date date = new Date(); 
//         txtdatechooser.setDate(date);
       
}
 public void setId() {
        try {
            String newId = IdGenerater.getNewId("batch", "bchid", "BH", 2);
            txtBatchId.setText(newId);
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtsid = new javax.swing.JTextField();
        txtBatchId = new javax.swing.JTextField();
        btnSearch = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbatch = new javax.swing.JTable();
        txtdatechooser = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        combogrnid = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        addnew_btn = new javax.swing.JToggleButton();
        remove_btn = new javax.swing.JToggleButton();
        updatebtn = new javax.swing.JToggleButton();
        save_btn = new javax.swing.JToggleButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Manage Batch");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Supplier Id");

        txtsid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsidActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Batch ID");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Date");

        tblbatch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "     Brand name", "     GRN ID", "     Brand Id", "      Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblbatch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbatchMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblbatch);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("GRN ID");

        combogrnid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combogrnidItemStateChanged(evt);
            }
        });
        combogrnid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combogrnidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdatechooser, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtBatchId, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btnSearch))
                            .addComponent(txtsid, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(combogrnid, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSearch))
                            .addComponent(txtBatchId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combogrnid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(txtdatechooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/asirisupermarket/images/10logos.png"))); // NOI18N

        addnew_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addnew_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/asirisupermarket/images/add2-64.png"))); // NOI18N
        addnew_btn.setText("Add ");
        addnew_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnew_btnActionPerformed(evt);
            }
        });

        remove_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        remove_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/asirisupermarket/images/Cancel_48px_1.png"))); // NOI18N
        remove_btn.setText("Remove");
        remove_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_btnActionPerformed(evt);
            }
        });

        updatebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updatebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/asirisupermarket/images/Save-icon.png"))); // NOI18N
        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        save_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        save_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/asirisupermarket/images/Save-icon.png"))); // NOI18N
        save_btn.setText("Save");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(193, 193, 193)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(addnew_btn)
                            .addGap(69, 69, 69)
                            .addComponent(remove_btn)
                            .addGap(94, 94, 94)
                            .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(91, 91, 91)
                            .addComponent(save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(344, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addnew_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remove_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
       SimpleDateFormat dat=new SimpleDateFormat("yyyy-MM-dd");
        //String date=dat.format(txtDatepicker.getDate());
        String date=dat.format(txtdatechooser.getDate());
        BatchDTO batch=new BatchDTO(
         txtBatchId.getText(),
         combogrnid.getSelectedItem().toString(),
         txtsid.getText(),
            date);

        try {

            boolean result = ManageBatchController.batchDAO.update(batch);
            if (result) {
                JOptionPane.showMessageDialog(this, "Batch has been successfully updated");
               // btn_refreshActionPerformed(evt);
               loadAllBatches(); 
                clearAllTextFileds();
            } else {
                JOptionPane.showMessageDialog(this, "Batch hasn't been updated");
            }

        } catch (Exception ex) {
            Logger.getLogger(ManageBatch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_save_btnActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String BCHID = txtBatchId.getText();
        try {
            searchBatch(BCHID);
        } catch (Exception ex) {
            Logger.getLogger(ManageBatch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed
    public void searchBatch(String BCHID) throws Exception {
       BatchDTO batchdto = ManageBatchController.batchDAO.search(BCHID);
        if (batchdto != null) {
            txtsid.setText(batchdto.getSID());
            combogrnid.setSelectedItem(batchdto.getGRNID());
             String date1=batchdto.getDate();
            Date dat2=new SimpleDateFormat("yyyy-MM-dd").parse(date1);
            txtdatechooser.setDate(dat2);
//            String date=batchdto.getDate();
//            Date dat=new SimpleDateFormat("yyyy-dd-MM").parse(date);
//            txtDatepicker.setDate(dat);
        }
    }
    private void txtsidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsidActionPerformed

    private void addnew_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnew_btnActionPerformed
               SimpleDateFormat date=new SimpleDateFormat("yyyy-MM-dd");
               //String dat=date.format(txtDatepicker.getDate());
               String dat=date.format(txtdatechooser.getDate());
                 BatchDTO batch = new BatchDTO(
                txtBatchId.getText(),
               combogrnid.getSelectedItem().toString(),
                txtsid.getText(),
                dat );
            
         try {
            
            boolean result = ManageBatchController.batchDAO.add(batch);
            if (result){
                JOptionPane.showMessageDialog(this, "Batch has been successfully added.");
                loadAllBatches(); 
                 clearAllTextFileds();
            }else{
                JOptionPane.showMessageDialog(this, "Batch hasn't been added ");
            }
            
        } catch (Exception ex) {
            Logger.getLogger(ManageBatch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addnew_btnActionPerformed

    private void remove_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_btnActionPerformed
       SimpleDateFormat date=new SimpleDateFormat("yyyy-MM-dd");
       String dat=date.format(txtdatechooser.getDate());
        BatchDTO batch = new BatchDTO(
               txtBatchId.getText(),
                combogrnid.getSelectedItem().toString(), 
               txtsid.getText(),
               dat);
              //txtDate.getText());
        try {
           
            boolean result = ManageBatchController.batchDAO.delete(batch);
            if (result){
                JOptionPane.showMessageDialog(this, "Batch has been successfully Removed.");
                loadAllBatches(); 
                 clearAllTextFileds();
            }else{
                JOptionPane.showMessageDialog(this, "Batch hasn't been Removed ");
            }
            
        } catch (Exception ex) {
            Logger.getLogger(ManageBatch.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_remove_btnActionPerformed

    private void tblbatchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbatchMouseClicked
        try {
                    if (tblbatch.getSelectedRow() == -1) return;
                    
                    String batchId= tblbatch.getValueAt(tblbatch.getSelectedRow(), 0).toString();
                    String grnId= tblbatch.getValueAt(tblbatch.getSelectedRow(), 1).toString();
                    String SID= tblbatch.getValueAt(tblbatch.getSelectedRow(), 2).toString();
                    String localDate = tblbatch.getValueAt(tblbatch.getSelectedRow(), 3).toString();
                    
                     Date dat=new SimpleDateFormat("yyyy-MM-dd").parse(localDate);
                  // SimpleDateFormat dat=new SimpleDateFormat("yyyy-MM-dd");
                  //  String date=dat.format(txtDatepicker.getDate());
                    
                    txtBatchId.setText(batchId);
                    combogrnid.setSelectedItem(grnId);
                    txtsid.setText(SID);
                    txtdatechooser.setDate(dat);
                } catch (ParseException ex) {
                    Logger.getLogger(ManageBatch.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_tblbatchMouseClicked

    private void combogrnidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combogrnidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combogrnidActionPerformed

    private void combogrnidItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combogrnidItemStateChanged
        try {
            if(combogrnid.getSelectedIndex()==-1){return;}
            
            GrnDTO grn=ManageGRNController.grnDAO.search(new GrnDTO(combogrnid.getSelectedItem().toString(),null, null, null));
            if(grn==null){return;}
            txtsid.setText(grn.getSID());
        } catch (Exception ex) {
            Logger.getLogger(ManageBatch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_combogrnidItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addnew_btn;
    private javax.swing.JToggleButton btnSearch;
    private javax.swing.JComboBox<String> combogrnid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton remove_btn;
    private javax.swing.JToggleButton save_btn;
    private javax.swing.JTable tblbatch;
    private javax.swing.JTextField txtBatchId;
    private com.toedter.calendar.JDateChooser txtdatechooser;
    private javax.swing.JTextField txtsid;
    private javax.swing.JToggleButton updatebtn;
    // End of variables declaration//GEN-END:variables

    private void loadAllBatches() {
        
           
        try {
            ArrayList<BatchDTO> allBatchs = ManageBatchController.batchDAO.getAll();
            
            DefaultTableModel dtm = (DefaultTableModel) tblbatch.getModel();
            
            dtm.setRowCount(0);
            
            if (allBatchs != null){
                
                for (BatchDTO batch : allBatchs) {
                    
                    Object[] rowData = {
                        batch.getBID(),
                        batch.getGRNID(),
                        batch.getSID(),
                        batch.getDate()
                    };
                    
                    dtm.addRow(rowData);
                    
                }
                
            }   } catch (Exception ex) {
            Logger.getLogger(ManageBatch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    private void clearAllTextFileds() {
        txtBatchId.setText("");
        txtsid.setText("");
        txtdatechooser.setDate(null);
    }

    
   /* private Date parseDate(String date){
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        try {
            return sdf.parse(date);
        } catch (ParseException ex) {
            Logger.getLogger(ManageEmployee.class.getName()).log(Level.SEVERE, null, ex);
            return null;            
        }
    }*/
    
     private void loadSystemDate() {
        Date d1 = new Date(); //Current System date
        //SimpleDateFormat df = new SimpleDateFormat("YYYY-MM-dd");
        //String formatDate = df.format(d1);
        txtdatechooser.setDate(d1);

    }

    private void loadallgrnids() {
        try {
            combogrnid.removeAllItems();
            ArrayList<GrnDTO>alghrnid=ManageGRNController.grnDAO.getAll();
            if(alghrnid==null){return;}
            
            for(GrnDTO grn:alghrnid){
                combogrnid.addItem(grn.getGRNID());
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageBatch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

   }