/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.asirisupermarket.subpanels;

import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.asirisupermarket.controller.ManageCustomerController;
import lk.ijse.asirisupermarket.controller.ManageEmployeeController;
import lk.ijse.asirisupermarket.controller.ManageOrdersController;
import lk.ijse.asirisupermarket.controller.ManageProductController;
import lk.ijse.asirisupermarket.core.dto.CustomerDTO;
import lk.ijse.asirisupermarket.core.dto.EmployeeDTO;
import lk.ijse.asirisupermarket.core.dto.OrderDetailDTO;
import lk.ijse.asirisupermarket.core.dto.OrdersDTO;
import lk.ijse.asirisupermarket.core.dto.ProductDTO;
import lk.ijse.asirisupermarket.idgenerater.IdGenerater;
import lk.ijse.asirisupermarket.view.Calculator;
import lk.ijse.asirisupermarket.view.MainWindow;
import lk.ijse.asirisupermarketsystem.panel.OrdersPanel;
//import lk.ijse.jasper.Report;

/**
 *
 * @author Hafees
 */
//@Report("lk.ijse.asirisupermarket.report")
public class ManageOrder extends javax.swing.JPanel {
      
     public  static String cid;
    public ManageOrder() {
        initComponents();
        loadAllCustomerIds();
        loadAllproductCodes();
        loadSystemDate();
        loademployeeid();
        setId();
      
        //tblorder.setBackground(Color.GREEN);
     
        //setInvId();
        clearfields();
         
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        description_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        soh_txt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        qty_txt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        productcode_combobx = new javax.swing.JComboBox<>();
        price_txt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtBrId = new javax.swing.JTextField();
        txtcatID = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtOrdId = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        employeecombo = new javax.swing.JComboBox<>();
        txtdate = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        combobx1custid = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtcustname = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        txtamount = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txttotalamount = new javax.swing.JTextField();
        btndelete = new javax.swing.JToggleButton();
        jLabel20 = new javax.swing.JLabel();
        txtdiscount = new javax.swing.JTextField();
        btnfinalpayment = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblorder = new javax.swing.JTable();
        btndone = new javax.swing.JToggleButton();
        txttotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txttotalqty = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txttotalitem = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btn_calculater = new javax.swing.JToggleButton();
        cancel_btn1 = new javax.swing.JToggleButton();
        btnupdate1 = new javax.swing.JToggleButton();
        addnew_btn = new javax.swing.JToggleButton();
        imagepanel = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        lblimage = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1097, 629));
        setMinimumSize(new java.awt.Dimension(1097, 629));

        panel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Manage Order");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product detail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 0, 255));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Product Code ");

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("  Description ");

        description_txt.setEditable(false);
        description_txt.setBackground(new java.awt.Color(255, 255, 255));
        description_txt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        description_txt.setBorder(null);
        description_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                description_txtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Brand ");

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Category ");

        soh_txt.setEditable(false);
        soh_txt.setBackground(new java.awt.Color(255, 255, 255));
        soh_txt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        soh_txt.setBorder(null);
        soh_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soh_txtActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel14.setText("SOH ");

        qty_txt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        qty_txt.setBorder(null);
        qty_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qty_txtActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Qty ");

        productcode_combobx.setEditable(true);
        productcode_combobx.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 2));
        productcode_combobx.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                productcode_combobxItemStateChanged(evt);
            }
        });
        productcode_combobx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productcode_combobxActionPerformed(evt);
            }
        });
        productcode_combobx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                productcode_combobxKeyPressed(evt);
            }
        });

        price_txt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        price_txt.setBorder(null);
        price_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price_txtActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Price ");

        txtBrId.setEditable(false);
        txtBrId.setBackground(new java.awt.Color(255, 255, 255));
        txtBrId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtBrId.setBorder(null);
        txtBrId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrIdActionPerformed(evt);
            }
        });

        txtcatID.setEditable(false);
        txtcatID.setBackground(new java.awt.Color(255, 255, 255));
        txtcatID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtcatID.setBorder(null);
        txtcatID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcatIDActionPerformed(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(0, 0, 255));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 255));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 255));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 255));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 255));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(productcode_combobx, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(description_txt))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txtBrId, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12)
                        .addComponent(txtcatID, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(soh_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addComponent(price_txt))
                        .addGap(29, 29, 29)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(qty_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(jSeparator10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(soh_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txtcatID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator8)
                            .addComponent(jSeparator7))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtBrId, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(description_txt)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(price_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(qty_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(productcode_combobx, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(0, 0, 204));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Order no");

        txtOrdId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtOrdId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOrdId.setBorder(null);
        txtOrdId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrdIdActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("User Id");

        employeecombo.setEditable(true);
        employeecombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                employeecomboItemStateChanged(evt);
            }
        });

        txtdate.setEditable(false);
        txtdate.setBackground(new java.awt.Color(255, 255, 255));
        txtdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdate.setBorder(null);
        txtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Date");

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Customer Id");

        combobx1custid.setEditable(true);
        combobx1custid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 2));
        combobx1custid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combobx1custidItemStateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Customer name");

        txtcustname.setEditable(false);
        txtcustname.setBackground(new java.awt.Color(255, 255, 255));
        txtcustname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtcustname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcustname.setBorder(null);
        txtcustname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustnameActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 204));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 204));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel9))
                        .addComponent(txtOrdId, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel11))
                            .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(jLabel10)
                                .addGap(90, 90, 90))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(employeecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(combobx1custid, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcustname, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtOrdId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcustname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combobx1custid, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(employeecombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );

        jLabel19.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Amount Rs");

        txtamount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtamount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 2));
        txtamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtamountActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Total  Rs");

        txttotalamount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txttotalamount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 2));
        txttotalamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalamountActionPerformed(evt);
            }
        });
        txttotalamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttotalamountKeyPressed(evt);
            }
        });

        btndelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/asirisupermarket/images/Cancel.png"))); // NOI18N
        btndelete.setBorderPainted(false);
        btndelete.setContentAreaFilled(false);
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Discount Rs");

        txtdiscount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtdiscount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 2));
        txtdiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiscountActionPerformed(evt);
            }
        });

        btnfinalpayment.setBackground(new java.awt.Color(51, 51, 255));
        btnfinalpayment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnfinalpayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/asirisupermarket/images/payment-48_1.png"))); // NOI18N
        btnfinalpayment.setBorderPainted(false);
        btnfinalpayment.setContentAreaFilled(false);
        btnfinalpayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfinalpaymentActionPerformed(evt);
            }
        });
        btnfinalpayment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnfinalpaymentKeyPressed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tblorder.setAutoCreateRowSorter(true);
        tblorder.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblorder.setForeground(new java.awt.Color(51, 51, 255));
        tblorder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "       CODE", "     DESCRIPTION", "     CATEGORY ID", "        PRICE", "      QTY", "     AMOUNT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblorder.setGridColor(new java.awt.Color(255, 0, 255));
        tblorder.setSelectionBackground(new java.awt.Color(51, 255, 0));
        tblorder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblorderMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblorder);

        btndone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btndone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/asirisupermarket/images/done.png"))); // NOI18N
        btndone.setBorderPainted(false);
        btndone.setContentAreaFilled(false);
        btndone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoneActionPerformed(evt);
            }
        });

        txttotal.setEditable(false);
        txttotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txttotal.setForeground(new java.awt.Color(255, 51, 204));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Total");

        txttotalqty.setEditable(false);
        txttotalqty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txttotalqty.setForeground(new java.awt.Color(255, 51, 255));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Total qty");

        txttotalitem.setEditable(false);
        txttotalitem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txttotalitem.setForeground(new java.awt.Color(255, 51, 255));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Total item");

        btn_calculater.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/asirisupermarket/images/calculater.png"))); // NOI18N
        btn_calculater.setBorderPainted(false);
        btn_calculater.setContentAreaFilled(false);
        btn_calculater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calculaterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btn_calculater, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(txttotalitem, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(txttotalqty, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btndone, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btndone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_calculater, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(txttotalqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)
                                .addComponent(txttotalitem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)))
                        .addContainerGap())))
        );

        cancel_btn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancel_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/asirisupermarket/images/esc-escape-keyboard-function-48.png"))); // NOI18N
        cancel_btn1.setBorderPainted(false);
        cancel_btn1.setContentAreaFilled(false);
        cancel_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btn1ActionPerformed(evt);
            }
        });

        btnupdate1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnupdate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/asirisupermarket/images/Refresh_1.png"))); // NOI18N
        btnupdate1.setBorderPainted(false);
        btnupdate1.setContentAreaFilled(false);
        btnupdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdate1ActionPerformed(evt);
            }
        });

        addnew_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addnew_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/asirisupermarket/images/add2-64.png"))); // NOI18N
        addnew_btn.setBorderPainted(false);
        addnew_btn.setContentAreaFilled(false);
        addnew_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnew_btnActionPerformed(evt);
            }
        });
        addnew_btn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addnew_btnKeyPressed(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));
        jDesktopPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 1, true));

        jDesktopPane1.setLayer(lblimage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout imagepanelLayout = new javax.swing.GroupLayout(imagepanel);
        imagepanel.setLayout(imagepanelLayout);
        imagepanelLayout.setHorizontalGroup(
            imagepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        imagepanelLayout.setVerticalGroup(
            imagepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(544, 544, 544)
                                .addComponent(cancel_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(btnupdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnfinalpayment, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(txtamount, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addnew_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtdiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttotalamount, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imagepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addnew_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(imagepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtamount, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtdiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttotalamount, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cancel_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnfinalpayment, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnupdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void description_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_description_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_description_txtActionPerformed

    private void txtOrdIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrdIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrdIdActionPerformed

    private void soh_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soh_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soh_txtActionPerformed

    private void qty_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qty_txtActionPerformed
        addnew_btn.setBackground(Color.BLUE);
        addnew_btn.requestFocus();
    }//GEN-LAST:event_qty_txtActionPerformed

    private void price_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price_txtActionPerformed
        price_txt.requestFocus();
    }//GEN-LAST:event_price_txtActionPerformed

    private void txtamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtamountActionPerformed
       txtdiscount.requestFocus();
    }//GEN-LAST:event_txtamountActionPerformed

    private void txttotalamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalamountActionPerformed
       btnfinalpayment.requestFocus();
    }//GEN-LAST:event_txttotalamountActionPerformed

    private void txtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateActionPerformed

    private void txtBrIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrIdActionPerformed

    private void txtcatIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcatIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcatIDActionPerformed

    private void txtcustnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcustnameActionPerformed

    private void combobx1custidItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combobx1custidItemStateChanged
        try {
            if (combobx1custid.getSelectedIndex() == -1) {
                return;
            }

            //CustomerDTO customer = ManageCustomerController.searchCustomer(new CustomerDTO(combobx1custid.getSelectedItem().toString(), null, null, null));
            CustomerDTO customer = ManageCustomerController.customerDAO.search(new CustomerDTO(combobx1custid.getSelectedItem().toString(), null, null, null, null, null, null, null));
            if (customer == null) {
                return;
            }

            txtcustname.setText(customer.getCustomer_FirstName());

        } catch (Exception ex) {
            Logger.getLogger(ManageOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_combobx1custidItemStateChanged

    private void productcode_combobxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_productcode_combobxItemStateChanged
        try {
            if (productcode_combobx.getSelectedIndex() == -1) {
                return;
            }

            // ProductDTO product = ManageItemsController.searchItem(new ItemDTO(itemCodeComboBox.getSelectedItem().toString(), null, null, 0));
            ProductDTO product = ManageProductController.productDAO.search(new ProductDTO(productcode_combobx.getSelectedItem().toString(), null, null, null, null, null, null, 0,null));
            if (product == null) {
                return;
            }

            description_txt.setText(product.getDESCRIPTION());
            txtBrId.setText(product.getBRNID());
            txtcatID.setText(product.getCATID());
            soh_txt.setText(product.getQty_on_hand() + "");
            price_txt.setText(product.getUnit_Price().toPlainString());
           imageformat=new ImageIcon(product.getprodimage());
           lblimage.setIcon(imageformat);
        } catch (Exception ex) {
            Logger.getLogger(ManageOrder.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_productcode_combobxItemStateChanged

    private void txtdiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiscountActionPerformed
       txttotalamount.requestFocus();
        double amount=Double.parseDouble(txtamount.getText());
        double discount=Double.parseDouble(txtdiscount.getText());
        double totalAmount = amount-discount;
       txttotalamount.setText(""+totalAmount);
      // btnsave.setForeground(Color.yellow);
       //btnsave.setToolTipText("Save and print invoice");
    }//GEN-LAST:event_txtdiscountActionPerformed

    private void btndoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoneActionPerformed
        double amount = 0;
        DefaultTableModel dtm = (DefaultTableModel) tblorder.getModel();
        for (int i = 0; i < dtm.getRowCount(); i++) {
            amount += Double.parseDouble(dtm.getValueAt(i, 5).toString());
        }
        txtamount.setText(""+amount);
        txtdiscount.requestFocus();
        

    }//GEN-LAST:event_btndoneActionPerformed
   
    
    private void addnew_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnew_btnActionPerformed
        //LoginFrame login=new LoginFrame();
       // login.setVisible(true);
       if((employeecombo.getSelectedIndex()==-1)|(combobx1custid.getSelectedIndex()==-1)|(productcode_combobx.getSelectedIndex()==-1)){
       JOptionPane.showMessageDialog(this,"Please select user,customer and product ");
       
       return;
       }
        addnew_btn.setBackground(null);
        addnew_btn.requestFocus();
        String itemCode = (String) productcode_combobx.getSelectedItem();
        String description = description_txt.getText();
        String catid = txtcatID.getText();
        double unitPrice = Double.parseDouble(price_txt.getText());
        int quty = Integer.parseInt(qty_txt.getText());
        double amount = unitPrice * quty;
//        Object[] rowData = {itemCode, description,catid, unitPrice, qty, amount};
        DefaultTableModel dtm = (DefaultTableModel) tblorder.getModel();
//        dtm.addRow(rowData);
        for (int i = 0; i < dtm.getRowCount(); i++) {
            if (dtm.getValueAt(i, 0).equals(itemCode)) {
                dtm.setValueAt(Integer.parseInt(dtm.getValueAt(i, 4).toString()) + quty, i, 4);
                dtm.setValueAt(Double.parseDouble(dtm.getValueAt(i, 5).toString())+amount, i, 5);
                clearFieldsaddbutton();
                 getsum();
                 getQty();
                itemItemcount();
                return;
            } else {

            }
        }
        Object[] rowData = {itemCode, description, catid, unitPrice, quty, amount};
        dtm.addRow(rowData);
         getsum();
         getQty();
         itemItemcount();
        clearFieldsaddbutton();
        productcode_combobx.requestFocus();
    }//GEN-LAST:event_addnew_btnActionPerformed

    private void productcode_combobxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productcode_combobxActionPerformed
       qty_txt.requestFocus();
    }//GEN-LAST:event_productcode_combobxActionPerformed

    private void btnfinalpaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfinalpaymentActionPerformed
        if (combobx1custid.getSelectedIndex() == -1) {
            return;
        }

        OrdersDTO order = new OrdersDTO(txtOrdId.getText(),
                combobx1custid.getSelectedItem().toString(),
                employeecombo.getSelectedItem().toString(),
                txtdate.getText());
         Date date = null;
        try {
            date = new SimpleDateFormat("yyyy-MM-dd").parse(txtdate.getText());
        } catch (ParseException ex) {
            Logger.getLogger(ManageOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
        ArrayList<OrderDetailDTO> alOrderDetails = new ArrayList<>();
         
        DefaultTableModel dtm = (DefaultTableModel) tblorder.getModel();
        for (int i = 0; i < dtm.getRowCount(); i++) {

            OrderDetailDTO orderDetail = new OrderDetailDTO(order.getOID(), dtm.getValueAt(i, 0).toString(),
                    Integer.parseInt(dtm.getValueAt(i, 4).toString()),
                    Double.parseDouble(dtm.getValueAt(i, 3).toString()));
            alOrderDetails.add(orderDetail);
        }
        try {
            boolean result = ManageOrdersController.ManageOrdersController(order, alOrderDetails);
              
            if (result) {
                   
                JOptionPane.showMessageDialog(this, "Order has been successfully placed");
                //setId();
                 PaymentFinal mn=new PaymentFinal();
        
                mn.lbloid.setText(txtOrdId.getText());
                mn.lblorddate.setText(txtdate.getText());
                mn.lblamount.setText(txtamount.getText());
                mn.lbldiscount.setText(txtdiscount.getText());
                mn.lbltotamount.setText(txttotalamount.getText());
                mn.lblcusid.setText(combobx1custid.getSelectedItem().toString());
                mn.lblempid.setText(employeecombo.getSelectedItem().toString());
                mn.setSize(panel1.getSize());
                panel1.removeAll();
                panel1.add(mn);
                panel1.repaint();
                panel1.revalidate();
                mn.txtpaidamount.setText(txttotalamount.getText());
                mn.txtpaidamount.selectAll();
                mn.txtpaidamount.requestFocus();
               // setInvId();
                clearfields();
            } else {
                  
                JOptionPane.showMessageDialog(this, "Order hasn't been placed ");
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnfinalpaymentActionPerformed

    private void addnew_btnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addnew_btnKeyPressed
        if((combobx1custid.getSelectedIndex()==-1)|(employeecombo.getSelectedIndex()==-1)){
           JOptionPane.showMessageDialog(this, "Please select User and customer"); 
           return;
        }
        
        addnew_btn.setBackground(null);
        
        //addnew_btn.requestFocus();
        String itemCode = (String) productcode_combobx.getSelectedItem();
        String description = description_txt.getText();
        String catid = txtcatID.getText();
        double unitPrice = Double.parseDouble(price_txt.getText());
        int qty = Integer.parseInt(qty_txt.getText());
        double amount = unitPrice * qty;
//        Object[] rowData = {itemCode, description,catid, unitPrice, qty, amount};
        DefaultTableModel dtm = (DefaultTableModel) tblorder.getModel();
//        dtm.addRow(rowData);
        for (int i = 0; i < dtm.getRowCount(); i++) {
            if (dtm.getValueAt(i, 0).equals(itemCode)) {
                dtm.setValueAt(Integer.parseInt(dtm.getValueAt(i, 4).toString()) + qty, i, 4);
                dtm.setValueAt(Double.parseDouble(dtm.getValueAt(i, 5).toString())+amount, i, 5);
              
                  getsum();
                 getQty();
                 itemItemcount();
                return;
                
            } else {

            }
        }
        Object[] rowData = {itemCode, description, catid, unitPrice, qty, amount};
        dtm.addRow(rowData);
         getsum();
         getQty();
         itemItemcount();
        clearFieldsaddbutton();
        productcode_combobx.requestFocus();
        
    }//GEN-LAST:event_addnew_btnKeyPressed

    private void employeecomboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_employeecomboItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_employeecomboItemStateChanged

    private void cancel_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btn1ActionPerformed
        OrdersPanel mn=new OrdersPanel();
        MainWindow nm=new MainWindow();
        setVisible(false);
       
    }//GEN-LAST:event_cancel_btn1ActionPerformed

    private void btnupdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdate1ActionPerformed
       if(tblorder.getSelectedRow()==-1){
       JOptionPane.showMessageDialog(this, "Please select the product to update");
       return;
       }
        int i=tblorder.getSelectedRow();
        String code=productcode_combobx.getSelectedItem().toString();
       int qty=Integer.parseInt(qty_txt.getText());
       double unitprice=Double.parseDouble(price_txt.getText());
       double amount=qty*unitprice;
       
       DefaultTableModel model=(DefaultTableModel) tblorder.getModel();
       if(i>0){
       model.setValueAt(code, i, 0);
       model.setValueAt(description_txt.getText(), i, 1);
       model.setValueAt(txtcatID.getText(), i, 2);
       model.setValueAt(price_txt.getText(), i, 3);
       model.setValueAt(qty, i, 4);
       model.setValueAt(amount, i, 5);
       }
            getsum();
         getQty();
         itemItemcount();
       clearFieldsaddbutton();
    }//GEN-LAST:event_btnupdate1ActionPerformed

    private void txttotalamountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttotalamountKeyPressed
       btnfinalpayment.setBackground(Color.green);
    }//GEN-LAST:event_txttotalamountKeyPressed

    private void btnfinalpaymentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnfinalpaymentKeyPressed
     if (combobx1custid.getSelectedIndex() == -1) {
            return;
        }

        OrdersDTO order = new OrdersDTO(txtOrdId.getText(),
                combobx1custid.getSelectedItem().toString(),
                employeecombo.getSelectedItem().toString(),
                txtdate.getText());
         Date date = null;
        try {
            date = new SimpleDateFormat("yyyy-MM-dd").parse(txtdate.getText());
        } catch (ParseException ex) {
            Logger.getLogger(ManageOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
        ArrayList<OrderDetailDTO> alOrderDetails = new ArrayList<>();
         
        DefaultTableModel dtm = (DefaultTableModel) tblorder.getModel();
        for (int i = 0; i < dtm.getRowCount(); i++) {

            OrderDetailDTO orderDetail = new OrderDetailDTO(order.getOID(), dtm.getValueAt(i, 0).toString(),
                    Integer.parseInt(dtm.getValueAt(i, 4).toString()),
                    Double.parseDouble(dtm.getValueAt(i, 3).toString()));
            alOrderDetails.add(orderDetail);
        }
        try {
            boolean result = ManageOrdersController.ManageOrdersController(order, alOrderDetails);
              
            if (result) {
                   
                JOptionPane.showMessageDialog(this, "Order has been successfully placed");
                //setId();
                 PaymentFinal mn=new PaymentFinal();
        
                mn.lbloid.setText(txtOrdId.getText());
                mn.lblorddate.setText(txtdate.getText());
                mn.lblamount.setText(txtamount.getText());
                mn.lbldiscount.setText(txtdiscount.getText());
                mn.lbltotamount.setText(txttotalamount.getText());
                mn.lblcusid.setText(combobx1custid.getSelectedItem().toString());
                mn.lblempid.setText(employeecombo.getSelectedItem().toString());
                mn.setSize(panel1.getSize());
                panel1.removeAll();
                panel1.add(mn);
                panel1.repaint();
                panel1.revalidate();
                mn.txtpaidamount.setText(txttotalamount.getText());
                mn.txtpaidamount.selectAll();
                mn.txtpaidamount.requestFocus();
               // setInvId();
                clearfields();
            } else {
                  
                JOptionPane.showMessageDialog(this, "Order hasn't been placed ");
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnfinalpaymentKeyPressed

    private void productcode_combobxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productcode_combobxKeyPressed
       productcode_combobx.setPopupVisible(true);
               
    }//GEN-LAST:event_productcode_combobxKeyPressed

    private void tblorderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblorderMouseClicked
       if(tblorder.getSelectedRow()==-1)return;
       
       String code=tblorder.getValueAt(tblorder.getSelectedRow(), 0).toString();
       String description=tblorder.getValueAt(tblorder.getSelectedRow(), 1).toString();
       String catid=tblorder.getValueAt(tblorder.getSelectedRow(), 2).toString();
       String price=tblorder.getValueAt(tblorder.getSelectedRow(), 3).toString();
       String qty=tblorder.getValueAt(tblorder.getSelectedRow(), 4).toString();
       String amount=tblorder.getValueAt(tblorder.getSelectedRow(), 5).toString();
       
       productcode_combobx.setSelectedItem(code);
       description_txt.setText(description);
       txtcatID.setText(catid);
       qty_txt.setText(qty);
       price_txt.setText(price);
    }//GEN-LAST:event_tblorderMouseClicked

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
      // new ManagerPasswordForm().setVisible(true);
//       DefaultTableModel dtm=(DefaultTableModel) tblorder.getModel();
//       int selectedrow=tblorder.getSelectedRow();
//       if(selectedrow>0){
//        dtm.removeRow(selectedrow);
        deleteActionPerformed();
         getsum();
         getQty();
         itemItemcount();
       
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btn_calculaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calculaterActionPerformed
       new Calculator().setVisible(true);
    }//GEN-LAST:event_btn_calculaterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addnew_btn;
    private javax.swing.JToggleButton btn_calculater;
    public static javax.swing.JToggleButton btndelete;
    private javax.swing.JToggleButton btndone;
    public static javax.swing.JToggleButton btnfinalpayment;
    private javax.swing.JToggleButton btnupdate1;
    private javax.swing.JToggleButton cancel_btn1;
    public static javax.swing.JComboBox<String> combobx1custid;
    private javax.swing.JTextField description_txt;
    public static javax.swing.JComboBox<String> employeecombo;
    private javax.swing.JPanel imagepanel;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblimage;
    private javax.swing.JPanel panel1;
    private javax.swing.JTextField price_txt;
    private javax.swing.JComboBox<String> productcode_combobx;
    private javax.swing.JTextField qty_txt;
    private javax.swing.JTextField soh_txt;
    public static javax.swing.JTable tblorder;
    private javax.swing.JTextField txtBrId;
    public static javax.swing.JTextField txtOrdId;
    public static javax.swing.JTextField txtamount;
    private javax.swing.JTextField txtcatID;
    private javax.swing.JTextField txtcustname;
    public static javax.swing.JTextField txtdate;
    public static javax.swing.JTextField txtdiscount;
    private javax.swing.JTextField txttotal;
    public static javax.swing.JTextField txttotalamount;
    private javax.swing.JTextField txttotalitem;
    private javax.swing.JTextField txttotalqty;
    // End of variables declaration//GEN-END:variables
    private  ImageIcon imageformat;
    
    public void setId() {
        try {
            String newId = IdGenerater.getNewId("ORDERS", "OID", "D", 2);
            txtOrdId.setText(newId);
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    
     

    private void loadSystemDate() {
        Date d1 = new Date(); //Current System date
        SimpleDateFormat df = new SimpleDateFormat("YYYY-MM-dd");
        String formatDate = df.format(d1);
        txtdate.setText(formatDate);

    }

    private Date parseDate(String date) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        try {
            return sdf.parse(date);
        } catch (ParseException ex) {
            Logger.getLogger(ManageOrder.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }
    }

    private void loadAllCustomerIds() {
        try {
            ArrayList<CustomerDTO> allCustomers = ManageCustomerController.customerDAO.getAll();

            combobx1custid.removeAllItems();
            if (allCustomers == null) {
                return;
            }

            for (CustomerDTO customer : allCustomers) {
                combobx1custid.addItem(customer.getCID());
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void clearfields(){
    DefaultTableModel model=(DefaultTableModel) tblorder.getModel();
     model.setRowCount(0);
     combobx1custid.setSelectedIndex(-1);
      productcode_combobx.setSelectedIndex(-1);
      txtcustname.setText("");
      employeecombo.setSelectedIndex(-1);
        txtBrId.setText("");
        txtamount.setText("");
        txtcatID.setText("");
        txtdiscount.setText("");
        description_txt.setText("");
        qty_txt.setText("");
        soh_txt.setText("");
        price_txt.setText("");
        txttotalamount.setText("");
    }
    
    private void clearFieldsaddbutton(){
      productcode_combobx.setSelectedIndex(-1);
        txtBrId.setText("");
        txtamount.setText("");
        txtcatID.setText("");
        txtdiscount.setText("");
        description_txt.setText("");
        qty_txt.setText("");
        soh_txt.setText("");
        price_txt.setText("");
        txttotalamount.setText("");
    
    
    
    }
    private void loadAllproductCodes() {
        try {
            ArrayList<ProductDTO> allproducts = ManageProductController.productDAO.getAll();
            productcode_combobx.removeAllItems();
            if (allproducts == null) {
                return;
            }

            for (ProductDTO product : allproducts) {
                productcode_combobx.addItem(product.getCODE());
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void loademployeeid() {    
        try {
            ArrayList<EmployeeDTO> allemployee = ManageEmployeeController.employeeDAO.getAll();
            employeecombo.removeAllItems();
            if (allemployee == null) {
                return;
            }

            for (EmployeeDTO employee : allemployee) {
                employeecombo.addItem(employee.getEID());
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void deleteActionPerformed(){
     DefaultTableModel model=(DefaultTableModel) tblorder.getModel();
        int i=tblorder.getSelectedRow();
        if (i>0){
         model.removeRow(i);
        }
       
        clearFieldsaddbutton();
    
    }
     public void getsum(){
      
          double sum=0;
          for(int i=0; i<tblorder.getRowCount(); i++){
          
              sum = sum + Double.parseDouble(tblorder.getValueAt(i,5).toString());
          }
          txttotal.setText(Double.toString(sum));
      }
     public  void getQty(){
     int qty=0;
     for(int i=0;i<tblorder.getRowCount();i++){
     qty +=Integer.parseInt(tblorder.getValueAt(i, 4).toString());
     }
     txttotalqty.setText(Integer.toString(qty));
     }
     public void itemItemcount(){
     int item=0;
     for(int i=0;i<tblorder.getRowCount();i++){
     //item +=tblorder.getRowCount();
     }
      item +=tblorder.getRowCount();
     txttotalitem.setText(Integer.toString(item));
     }
}      
