/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.asirisupermarket.subpanels;

import java.awt.Dialog;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.asirisupermarket.controller.ManagePaymentController;
import lk.ijse.asirisupermarket.core.dto.PaymentDTO;
import lk.ijse.asirisupermarket.dao.db.DBConnection;
import lk.ijse.asirisupermarket.idgenerater.IdGenerater;
import lk.ijse.asirisupermarket.view.MainWindow;
import lk.ijse.asirisupermarketsystem.panel.ManagePayments;
//import lk.ijse.jasper.IJSEJasperViewer;
//import lk.ijse.jasper.JasperUtil;
//import lk.ijse.jasper.Report;
//import net.sf.jasperreports.engine.JRException;
//import net.sf.jasperreports.engine.JasperFillManager;
//import net.sf.jasperreports.engine.JasperPrint;
//import net.sf.jasperreports.engine.JasperReport;
//import net.sf.jasperreports.engine.JasperReportsContext;

/**
 *
 * @author Hafees
 */
//@Report("lk.ijse.asirisupermarket.report")
public class PaymentFinal extends javax.swing.JPanel {
 
    
    
   
    /**Man
     * Creates new form PaymentFinal
     */
    public PaymentFinal() {
        initComponents();
        setId();
    
        
    
   
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtpaidamount = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        lblchange = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbloid = new javax.swing.JLabel();
        lblorddate = new javax.swing.JLabel();
        lbldiscount = new javax.swing.JLabel();
        lblamount = new javax.swing.JLabel();
        lbltotamount = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        btnprint = new javax.swing.JToggleButton();
        btnexport = new javax.swing.JToggleButton();
        btnsave = new javax.swing.JToggleButton();
        btnexport1 = new javax.swing.JToggleButton();
        jLabel30 = new javax.swing.JLabel();
        lblInvoice = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        lblcusid = new javax.swing.JLabel();
        lblempid = new javax.swing.JLabel();
        btnviewpayment = new javax.swing.JToggleButton();

        panel1.setBackground(new java.awt.Color(102, 255, 102));

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Order Id");

        jLabel19.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Order Date");

        jLabel20.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Discount");

        jLabel21.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Amount");

        jLabel22.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 0, 204));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Rs");

        jLabel23.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Paid Amount");

        txtpaidamount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtpaidamount.setForeground(new java.awt.Color(255, 0, 0));
        txtpaidamount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));
        txtpaidamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpaidamountActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Balance Amount");

        lblchange.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblchange.setForeground(new java.awt.Color(204, 0, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Payment Details");

        lbloid.setBackground(new java.awt.Color(102, 255, 102));
        lbloid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbloid.setForeground(new java.awt.Color(0, 0, 204));
        lbloid.setOpaque(true);

        lblorddate.setBackground(new java.awt.Color(102, 255, 102));
        lblorddate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblorddate.setForeground(new java.awt.Color(0, 0, 204));
        lblorddate.setOpaque(true);

        lbldiscount.setBackground(new java.awt.Color(102, 255, 102));
        lbldiscount.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbldiscount.setForeground(new java.awt.Color(204, 0, 204));
        lbldiscount.setOpaque(true);

        lblamount.setBackground(new java.awt.Color(102, 255, 102));
        lblamount.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblamount.setForeground(new java.awt.Color(204, 0, 204));
        lblamount.setOpaque(true);

        lbltotamount.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbltotamount.setForeground(new java.awt.Color(204, 0, 204));

        jLabel27.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 0, 204));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("Rs");

        jLabel28.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(204, 0, 204));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("Rs");

        jLabel25.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("Total Amount");

        jLabel26.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 0, 204));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("Rs");

        jLabel29.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(204, 0, 204));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText("Rs");

        btnprint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnprint.setText("Print");

        btnexport.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnexport.setText("Cancel");
        btnexport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexportActionPerformed(evt);
            }
        });

        btnsave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsave.setText("Save ");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnexport1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnexport1.setText("Export");
        btnexport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexport1ActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("Invoice No");

        lblInvoice.setBackground(new java.awt.Color(102, 255, 102));
        lblInvoice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblInvoice.setForeground(new java.awt.Color(0, 0, 204));
        lblInvoice.setOpaque(true);

        jLabel31.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel31.setText("Employee Id");

        jLabel32.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel32.setText("Customer Id");

        lblcusid.setBackground(new java.awt.Color(102, 255, 102));
        lblcusid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblcusid.setForeground(new java.awt.Color(0, 0, 204));
        lblcusid.setOpaque(true);

        lblempid.setBackground(new java.awt.Color(102, 255, 102));
        lblempid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblempid.setForeground(new java.awt.Color(0, 0, 204));
        lblempid.setOpaque(true);

        btnviewpayment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnviewpayment.setText("View Payment");
        btnviewpayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewpaymentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbloid, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblamount, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel19)
                .addGap(45, 45, 45)
                .addComponent(lblorddate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lbltotamount, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lblcusid, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txtpaidamount, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel31)
                .addGap(42, 42, 42)
                .addComponent(lblempid, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblchange, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnviewpayment)
                .addGap(71, 71, 71)
                .addComponent(btnexport)
                .addGap(86, 86, 86)
                .addComponent(btnexport1)
                .addGap(90, 90, 90)
                .addComponent(btnprint)
                .addGap(83, 83, 83)
                .addComponent(btnsave))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(lblamount, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(lbldiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(lblInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(lbloid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltotamount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblorddate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtpaidamount, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblcusid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblempid, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblchange, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnexport)
                        .addComponent(btnviewpayment))
                    .addComponent(btnexport1)
                    .addComponent(btnprint)
                    .addComponent(btnsave)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtpaidamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpaidamountActionPerformed
        double paidamt=Double.parseDouble(txtpaidamount.getText());
        double totalamt=Double.parseDouble(lbltotamount.getText());
        double balanceamt=paidamt-totalamt;
        if(paidamt<totalamt){
            JOptionPane.showMessageDialog(this, "Not Sufficeient Money");
        }else if
            (balanceamt>5000){
            JOptionPane.showMessageDialog(this, "Change above the allowed limit");
        }else{
        lblchange.setText(balanceamt+"0");
        }
        

    }//GEN-LAST:event_txtpaidamountActionPerformed

    private void btnexportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnexportActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
       
            PaymentDTO payment=new PaymentDTO(lblInvoice.getText(), lbloid.getText(),
                    lblcusid.getText(),
                    lblempid.getText(),lblorddate.getText(),
                    Double.parseDouble(lbldiscount.getText()),Double.parseDouble(lbltotamount.getText()));
            
             try {
            boolean status=ManagePaymentController.paymentDAO.add(payment);
            if (status) {
            JOptionPane.showMessageDialog(this,"Payment Has been Succesfully saved");
            new MainWindow().setVisible(true);
            this.setVisible(false);
            clearfields();
            }else{
             JOptionPane.showMessageDialog(this,"Payment Has Not  been  saved");
            }
        } catch (Exception ex) {
            Logger.getLogger(PaymentFinal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnviewpaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewpaymentActionPerformed
        ManagePayments mn=new ManagePayments();
        mn.setSize(panel1.getSize());
                panel1.removeAll();
                panel1.add(mn);
                panel1.repaint();
                panel1.revalidate();
    }//GEN-LAST:event_btnviewpaymentActionPerformed

    private void btnexport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexport1ActionPerformed
//          JasperUtil.init(PaymentFinal.class);
//        
//        JasperReportsContext ctx = JasperUtil.getReportContext();
//        
//        try {
//            JasperReport compiledReport = JasperUtil.
//                    getCompiledReport("NEWINVOICE_1.jasper");
//            
//            JasperFillManager fillManager = JasperFillManager.getInstance(ctx);
//            
//            HashMap<String, Object> reportParams = new HashMap<>();
//            
//            reportParams.put("INVOICE ID", lblInvoice.getText());
//            
//            Connection connection = DBConnection.getInstance().getConnection();
//            
//            JasperPrint filledReport = fillManager.
//                    fill(compiledReport, reportParams, connection);
//            
//            IJSEJasperViewer frmJasperViewer = new IJSEJasperViewer(filledReport);
//            frmJasperViewer.setTitle("Invoice Details");
//            frmJasperViewer.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
//            frmJasperViewer.setVisible(true);
//            
//        } catch (JRException ex) {
//            Logger.getLogger(PaymentFinal.class.getName()).log(Level.SEVERE, null, ex);
//        } 
    }//GEN-LAST:event_btnexport1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnexport;
    private javax.swing.JToggleButton btnexport1;
    private javax.swing.JToggleButton btnprint;
    private javax.swing.JToggleButton btnsave;
    private javax.swing.JToggleButton btnviewpayment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    public static javax.swing.JLabel lblInvoice;
    public static javax.swing.JLabel lblamount;
    public static javax.swing.JLabel lblchange;
    public static javax.swing.JLabel lblcusid;
    public static javax.swing.JLabel lbldiscount;
    public static javax.swing.JLabel lblempid;
    public static javax.swing.JLabel lbloid;
    public static javax.swing.JLabel lblorddate;
    public static javax.swing.JLabel lbltotamount;
    private javax.swing.JPanel panel1;
    public static javax.swing.JTextField txtpaidamount;
    // End of variables declaration//GEN-END:variables
  public void setId() {
        try {
            String newId = IdGenerater.getNewId("Payment", "PID", "INV", 3);
            lblInvoice.setText(newId);
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
  private void clearfields(){
    //lblInvoice.setText("");
    lblamount.setText("");
    lblchange.setText("");
    lblcusid.setText("");
     lbldiscount.setText("");
     lblempid.setText("");
    lbloid.setText("");
   lblorddate.setText("");
     lbltotamount.setText("");
   txtpaidamount.setText("");
  }
}

