/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.asirisupermarketsystem.panel;

import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.InputStream;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.asirisupermarket.controller.ManageEmployeeController;
import lk.ijse.asirisupermarket.core.dto.EmployeeDTO;
import lk.ijse.asirisupermarket.idgenerater.IdGenerater;
import lk.ijse.asirisupermarket.util.Validation;
import net.coobird.thumbnailator.Thumbnails;

/**
 *
 * @author Hafees
 */
public class ManageEmployee1 extends javax.swing.JPanel {
    private String gender=null;
    private  String dat=null;
    
    public ManageEmployee1() {
        initComponents();
          loadAllEmployees();
          setId();
        Date date=new Date();
        txtdatechooserdoj.setDate(date);
    }
      public void setId() {
        try {
            String newId = IdGenerater.getNewId("Employee", "EID", "E", 2);
            txtid.setText(newId);
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroup = new javax.swing.ButtonGroup();
        panel1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btn_new = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_print = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        imagelabel = new javax.swing.JDesktopPane();
        lblimage = new javax.swing.JLabel();
        btn_upload = new javax.swing.JToggleButton();
        txtimagepath = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        id_lbl = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        name_lbl1 = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        btnSearch = new javax.swing.JToggleButton();
        name_lbl3 = new javax.swing.JLabel();
        txtLastname = new javax.swing.JTextField();
        gender_lbl = new javax.swing.JLabel();
        jrbtn_male = new javax.swing.JRadioButton();
        jrbtn_female = new javax.swing.JRadioButton();
        name_lbl5 = new javax.swing.JLabel();
        mobilphn_lbl2 = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        email_lbl6 = new javax.swing.JLabel();
        txtPosition = new javax.swing.JTextField();
        name_lbl6 = new javax.swing.JLabel();
        txtdatechooserdoj = new com.toedter.calendar.JDateChooser();
        txtdobdatechooser = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        mobilphn_lbl1 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        email_lbl = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        name_lbl2 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1097, 629));
        setMinimumSize(new java.awt.Dimension(1097, 629));
        setPreferredSize(new java.awt.Dimension(1144, 629));

        panel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1097, 629));
        jPanel1.setMinimumSize(new java.awt.Dimension(1097, 629));
        jPanel1.setPreferredSize(new java.awt.Dimension(1144, 629));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Employee");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "    User Id", "      User Name", "   User Type", "Email Id"
            }
        ));
        jPanel1.add(jTable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15934, 324, 898, -1));

        tblEmployee.setAutoCreateRowSorter(true);
        tblEmployee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblEmployee.setForeground(new java.awt.Color(255, 0, 255));
        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Id", "User First name", "User Last name", "Gender", "Dob", "Address", "Basic salary", "Contact No", "  Email", "Position", "Image", "   DOJ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Byte.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblEmployee.setGridColor(new java.awt.Color(0, 0, 255));
        tblEmployee.setOpaque(false);
        tblEmployee.setSelectionForeground(new java.awt.Color(51, 255, 51));
        tblEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmployeeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblEmployee);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 402, 950, 203));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_new.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_new.setText("New");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        btn_save.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_update.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_print.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_print.setText("Print");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_new)
                .addGap(44, 44, 44)
                .addComponent(btn_save)
                .addGap(40, 40, 40)
                .addComponent(btn_update)
                .addGap(29, 29, 29)
                .addComponent(btn_delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btn_clear)
                .addGap(63, 63, 63)
                .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_update, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_new, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(btn_save, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 660, 50));

        imagelabel.setBackground(new java.awt.Color(204, 204, 204));
        imagelabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        imagelabel.setLayer(lblimage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout imagelabelLayout = new javax.swing.GroupLayout(imagelabel);
        imagelabel.setLayout(imagelabelLayout);
        imagelabelLayout.setHorizontalGroup(
            imagelabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagelabelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        imagelabelLayout.setVerticalGroup(
            imagelabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagelabelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 230, 210));

        btn_upload.setText("upload");
        btn_upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_uploadActionPerformed(evt);
            }
        });
        jPanel1.add(btn_upload, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 90, -1));
        jPanel1.add(txtimagepath, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 160, -1));

        jLabel2.setText("image path");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 60, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        id_lbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        id_lbl.setForeground(new java.awt.Color(0, 0, 204));
        id_lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        id_lbl.setText("ID ");

        txtid.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtid.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 3, true));

        name_lbl1.setBackground(new java.awt.Color(255, 255, 255));
        name_lbl1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        name_lbl1.setForeground(new java.awt.Color(0, 0, 204));
        name_lbl1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name_lbl1.setText(" First Name");

        txtFname.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtFname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 3, true));
        txtFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFnameActionPerformed(evt);
            }
        });
        txtFname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFnameKeyReleased(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        name_lbl3.setBackground(new java.awt.Color(255, 255, 255));
        name_lbl3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        name_lbl3.setForeground(new java.awt.Color(0, 0, 204));
        name_lbl3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name_lbl3.setText(" Last Name");

        txtLastname.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtLastname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 3, true));
        txtLastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastnameActionPerformed(evt);
            }
        });

        gender_lbl.setBackground(new java.awt.Color(255, 255, 255));
        gender_lbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        gender_lbl.setForeground(new java.awt.Color(0, 0, 204));
        gender_lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        gender_lbl.setText("Gender");

        btngroup.add(jrbtn_male);
        jrbtn_male.setText("Male");
        jrbtn_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtn_maleActionPerformed(evt);
            }
        });

        btngroup.add(jrbtn_female);
        jrbtn_female.setText("Female");
        jrbtn_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtn_femaleActionPerformed(evt);
            }
        });

        name_lbl5.setBackground(new java.awt.Color(255, 255, 255));
        name_lbl5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        name_lbl5.setForeground(new java.awt.Color(0, 0, 204));
        name_lbl5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name_lbl5.setText("DOB");

        mobilphn_lbl2.setBackground(new java.awt.Color(255, 255, 255));
        mobilphn_lbl2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        mobilphn_lbl2.setForeground(new java.awt.Color(0, 0, 204));
        mobilphn_lbl2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mobilphn_lbl2.setText("Salary");

        txtSalary.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtSalary.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 3, true));
        txtSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalaryActionPerformed(evt);
            }
        });

        email_lbl6.setBackground(new java.awt.Color(255, 255, 255));
        email_lbl6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        email_lbl6.setForeground(new java.awt.Color(0, 0, 204));
        email_lbl6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        email_lbl6.setText("Position");

        txtPosition.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtPosition.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 3, true));

        name_lbl6.setBackground(new java.awt.Color(255, 255, 255));
        name_lbl6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        name_lbl6.setForeground(new java.awt.Color(0, 0, 204));
        name_lbl6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name_lbl6.setText("DOJ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(id_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(name_lbl1)
                        .addGap(15, 15, 15)
                        .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(name_lbl3)
                        .addGap(22, 22, 22)
                        .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(gender_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jrbtn_male)
                        .addGap(33, 33, 33)
                        .addComponent(jrbtn_female))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(mobilphn_lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addComponent(name_lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtdobdatechooser, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(name_lbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(email_lbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(20, 20, 20)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPosition)
                                .addComponent(txtdatechooserdoj, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))))
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch))))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name_lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name_lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gender_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbtn_male)
                    .addComponent(jrbtn_female))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name_lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdobdatechooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mobilphn_lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email_lbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name_lbl6, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtdatechooserdoj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 360, 300));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        mobilphn_lbl1.setBackground(new java.awt.Color(255, 255, 255));
        mobilphn_lbl1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        mobilphn_lbl1.setForeground(new java.awt.Color(0, 0, 204));
        mobilphn_lbl1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mobilphn_lbl1.setText("Mobile Phone ");

        txtContact.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtContact.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 3, true));
        txtContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactActionPerformed(evt);
            }
        });

        email_lbl.setBackground(new java.awt.Color(255, 255, 255));
        email_lbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        email_lbl.setForeground(new java.awt.Color(0, 0, 204));
        email_lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        email_lbl.setText("Email ID ");

        txtEmail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 3, true));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        name_lbl2.setBackground(new java.awt.Color(255, 255, 255));
        name_lbl2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        name_lbl2.setForeground(new java.awt.Color(0, 0, 204));
        name_lbl2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name_lbl2.setText("Address");

        txtAddress.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtAddress.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 3, true));
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(mobilphn_lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(name_lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(email_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobilphn_lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 410, 150));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1144, Short.MAX_VALUE)
            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFnameActionPerformed
        txtLastname.requestFocus();
    }//GEN-LAST:event_txtFnameActionPerformed

    private void txtFnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFnameKeyReleased
        Validation.name(txtFname);
    }//GEN-LAST:event_txtFnameKeyReleased

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        txtPosition.requestFocus();
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        txtSalary.requestFocus();
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtLastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastnameActionPerformed
      
    }//GEN-LAST:event_txtLastnameActionPerformed

    private void txtContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactActionPerformed
        txtEmail.requestFocus();
    }//GEN-LAST:event_txtContactActionPerformed

    private void txtSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalaryActionPerformed
        txtContact.requestFocus();
    }//GEN-LAST:event_txtSalaryActionPerformed

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        clearAllTextFileds();
        btn_save.setEnabled(true);
        btn_new.setEnabled(false);
        btn_update.setEnabled(false);
        btn_delete.setEnabled(false);
        btn_clear.setEnabled(false);
    }//GEN-LAST:event_btn_newActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
       if(jrbtn_male.isSelected()){
       gender="Male";
       }else{
       gender="Female";
       }
       SimpleDateFormat date=new SimpleDateFormat("yyyy-MM-dd");
       String dat=date.format(txtdobdatechooser.getDate());
        String dat1=date.format(txtdatechooserdoj.getDate());
        EmployeeDTO employee = new EmployeeDTO(
            txtid.getText(),
            txtFname.getText(),
            txtLastname.getText(),
            gender,
            dat,
            txtAddress.getText(),
            new BigDecimal(txtSalary.getText()),
            txtContact.getText(),
            txtEmail.getText(),
            txtPosition.getText(),
            employeeimage,
            dat1);
            
        try {

            boolean result = ManageEmployeeController.employeeDAO.add(employee);
            if (result){
                JOptionPane.showMessageDialog(this, "Employee has been successfully added.");
                loadAllEmployees();
                clearAllTextFileds();
                setId();
                btn_save.setEnabled(false);
                btn_new.setEnabled(true);
                btn_update.setEnabled(true);
                btn_delete.setEnabled(true);
                btn_clear.setEnabled(true);
            }else{
                JOptionPane.showMessageDialog(this, "Employee hasn't been added ");
            }

        } catch (Exception ex) {
            Logger.getLogger(ManageEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        if(jrbtn_male.isSelected()){
        gender="Male";
        }else{
        gender="Female";
        }
        SimpleDateFormat date=new SimpleDateFormat("yyyy-MM-dd");
        String dat=date.format(txtdobdatechooser.getDate());
         String dat1=date.format(txtdatechooserdoj.getDate());
        EmployeeDTO employee = new EmployeeDTO(
            txtid.getText(),
            txtFname.getText(),
            txtLastname.getText(),
            gender,
            dat,
            txtAddress.getText(),
            new BigDecimal(txtSalary.getText()),
            txtContact.getText(),
            txtEmail.getText(),
            txtPosition.getText(),
                employeeimage,
                dat1);
        try {

            boolean result = ManageEmployeeController.employeeDAO.update(employee);
            if (result){
                JOptionPane.showMessageDialog(this, "Employee has been successfully updated");
                loadAllEmployees();
                clearAllTextFileds();
            }else{
                JOptionPane.showMessageDialog(this, "Employee hasn't been updated");
            }

        } catch (Exception ex) {
            Logger.getLogger(ManageEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        SimpleDateFormat date=new SimpleDateFormat("yyyy-MM-dd");
        String dat=date.format(txtdobdatechooser.getDate());
         String dat1=date.format(txtdatechooserdoj.getDate());
         if(jrbtn_male.isSelected()){
        gender="Male";
        }else{
        gender="Female";
        }
        EmployeeDTO employee = new EmployeeDTO(
            txtid.getText(),
            txtFname.getText(),
            txtLastname.getText(),
           gender,
            dat,
            txtAddress.getText(),
            new BigDecimal(txtSalary.getText()),
            txtContact.getText(),
            txtEmail.getText(),
            txtPosition.getText(),
            employeeimage,
              dat1);  
        try {

            boolean result = ManageEmployeeController.employeeDAO.delete(employee);
            if (result){
                JOptionPane.showMessageDialog(this, "Employee has been successfully deleted.");
                loadAllEmployees();
                clearAllTextFileds();
            }else{
                JOptionPane.showMessageDialog(this, "Employee hasn't been deleted ");
            }

        } catch (Exception ex) {
            Logger.getLogger(ManageEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        clearAllTextFileds();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        tblEmployee.setRowSelectionAllowed(true);
    }//GEN-LAST:event_btn_printActionPerformed

    private void jrbtn_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtn_femaleActionPerformed
        gender="Female";
    }//GEN-LAST:event_jrbtn_femaleActionPerformed

    private void jrbtn_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtn_maleActionPerformed
        gender="Male" ;
    }//GEN-LAST:event_jrbtn_maleActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String EID = txtid.getText();
        try {
            searchEmployee(EID);
        } catch (Exception ex) {
            Logger.getLogger(ManageEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btn_uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_uploadActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename=f.getAbsolutePath();
        txtimagepath.setText(filename);
        
        try {
            
            File image =new File(filename);
            
            BufferedImage thumbanail = Thumbnails.of(image).size(lblimage.getWidth(), lblimage.getHeight()).asBufferedImage();
            
            ByteArrayOutputStream os = new ByteArrayOutputStream();
            
            ImageIO.write(thumbanail, "jpeg", os);
            
            InputStream is = new ByteArrayInputStream(os.toByteArray());
            
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            
            byte[] buf = new byte[1024];  // 1 MB
            
            for(int readNum;(readNum = is.read(buf))!=-1;){
            
            bos.write(buf,0,readNum);
            }
            viewimage=new ImageIcon(thumbanail);
            lblimage.setIcon(viewimage);
            employeeimage=bos.toByteArray();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_uploadActionPerformed

    private void tblEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployeeMouseClicked
        try {    
                    if (tblEmployee.getSelectedRow() == -1) return;
                    
                    String employeeId= tblEmployee.getValueAt(tblEmployee.getSelectedRow(), 0).toString();
                    String employeefName= tblEmployee.getValueAt(tblEmployee.getSelectedRow(), 1).toString();
                    String employeeLName= tblEmployee.getValueAt(tblEmployee.getSelectedRow(), 2).toString();
                    String employeeGender= tblEmployee.getValueAt(tblEmployee.getSelectedRow(), 3).toString();
                    String employeeDob= tblEmployee.getValueAt(tblEmployee.getSelectedRow(), 4).toString();
                    String employeeAddtress= tblEmployee.getValueAt(tblEmployee.getSelectedRow(), 5).toString();
                    String employeeSalary= tblEmployee.getValueAt(tblEmployee.getSelectedRow(), 6).toString();
                    String employeeContactno= tblEmployee.getValueAt(tblEmployee.getSelectedRow(), 7).toString();
                    String employeeEmail= tblEmployee.getValueAt(tblEmployee.getSelectedRow(), 8).toString();
                    String employeePosition= tblEmployee.getValueAt(tblEmployee.getSelectedRow(), 9).toString();
                    byte[] imagedata =(byte[]) tblEmployee.getValueAt(tblEmployee.getSelectedRow(), 10);
                    String employeeDoJ= tblEmployee.getValueAt(tblEmployee.getSelectedRow(), 11).toString();
                    
                    Date dat=new SimpleDateFormat("yyyy-MM-dd").parse(employeeDob);
                     Date dat1=new SimpleDateFormat("yyyy-MM-dd").parse(employeeDoJ);
                     
                    txtid.setText(employeeId);
                    txtFname.setText(employeefName);
                    txtLastname.setText(employeeLName);
                    
                    if(employeeGender.equals("Male")){
                    jrbtn_male.setSelected(true);
                    jrbtn_female.setSelected(false);
                    }else{
                     jrbtn_male.setSelected(false);
                    jrbtn_female.setSelected(true);
                    }
                    
                    txtdobdatechooser.setDate(dat);
                    txtAddress.setText(employeeAddtress);
                    txtSalary.setText(employeeSalary);
                    txtContact.setText(employeeContactno);
                    txtEmail.setText(employeeEmail);
                    txtPosition.setText(employeePosition);
                    txtSalary.setText(employeeSalary);
                    formate =new ImageIcon(imagedata);
                    lblimage.setIcon(formate);
                    txtdatechooserdoj.setDate(dat1);
                   // employeeimage=imagedata;
                } catch (ParseException ex) {
                    Logger.getLogger(ManageEmployee1.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_tblEmployeeMouseClicked
  
    
     public void searchEmployee(String EID) throws Exception {
       EmployeeDTO employeedto = ManageEmployeeController.employeeDAO.search(EID);
        if (employeedto != null) {
            gender=employeedto.getEmployee_Gender();
            if(gender.equals("Male")){
            jrbtn_male.setSelected(true);
            jrbtn_female.setSelected(false);
            }else{
            jrbtn_male.setSelected(false);
            jrbtn_female.setSelected(true);
            }
              txtFname.setText(employeedto.getEmployee_FirstName());
             txtLastname.setText(employeedto.getEmployee_LastName());
               
              String date=employeedto.getDate_Of_Birth();
              Date date1=new SimpleDateFormat("yyyy-MM-dd").parse(date);
              txtdobdatechooser.setDate(date1);
                txtAddress.setText(employeedto.getEmployee_Address());
                txtSalary.setText(employeedto.getBasic_Salary().toPlainString());
                txtContact.setText(employeedto.getContact_No());
                txtEmail.setText(employeedto.getEmployee_Email());
                txtPosition.setText(employeedto.getPosition());
               byte[]image =employeedto.getEmployeeimage();
               formate=new ImageIcon(image);
                lblimage.setIcon(formate);
                String date2=employeedto.getempdoj();
              Date date3=new SimpleDateFormat("yyyy-MM-dd").parse(date2);
              txtdatechooserdoj.setDate(date3);
               // employeeimage=image;
        }
        

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnSearch;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_update;
    private javax.swing.JToggleButton btn_upload;
    private javax.swing.ButtonGroup btngroup;
    private javax.swing.JLabel email_lbl;
    private javax.swing.JLabel email_lbl6;
    private javax.swing.JLabel gender_lbl;
    private javax.swing.JLabel id_lbl;
    private javax.swing.JDesktopPane imagelabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton jrbtn_female;
    private javax.swing.JRadioButton jrbtn_male;
    private javax.swing.JLabel lblimage;
    private javax.swing.JLabel mobilphn_lbl1;
    private javax.swing.JLabel mobilphn_lbl2;
    private javax.swing.JLabel name_lbl1;
    private javax.swing.JLabel name_lbl2;
    private javax.swing.JLabel name_lbl3;
    private javax.swing.JLabel name_lbl5;
    private javax.swing.JLabel name_lbl6;
    private javax.swing.JPanel panel1;
    private javax.swing.JTable tblEmployee;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtSalary;
    private com.toedter.calendar.JDateChooser txtdatechooserdoj;
    private com.toedter.calendar.JDateChooser txtdobdatechooser;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtimagepath;
    // End of variables declaration//GEN-END:variables

    private void loadAllEmployees() {
        try {
           
           ArrayList<EmployeeDTO> allEmployees = ManageEmployeeController.employeeDAO.getAll();
            
            DefaultTableModel dtm = (DefaultTableModel) tblEmployee.getModel();
            
            dtm.setRowCount(0);
            
            if (allEmployees != null){
                
                for (EmployeeDTO employee : allEmployees) {
                    
                    Object[] rowData = {
                        employee.getEID(),
                        employee.getEmployee_FirstName(),
                        employee.getEmployee_LastName(),
                        employee.getEmployee_Gender(),
                        employee.getDate_Of_Birth(),
                        employee.getEmployee_Address(),
                        employee.getBasic_Salary(),
                        employee.getContact_No(),
                        employee.getEmployee_Email(),
                        employee.getPosition(),
                        employee.getEmployeeimage(),
                        employee.getempdoj(),
                    };
                    dtm.addRow(rowData);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageEmployee1     .class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void clearAllTextFileds() {
                 //txtid.setText("");
                txtFname.setText("");
                txtLastname.setText("");
                txtdobdatechooser.setDate(null);
                btngroup.clearSelection();
                lblimage.setIcon(null);
                txtAddress.setText("");
                txtSalary.setText("");
                txtContact.setText("");
                txtEmail.setText("");
                txtPosition.setText("");
                txtimagepath.setText("");
    }
     private void rowSelection(){
        int raw=tblEmployee.getSelectedRow();
        if(raw> -1){
        tblEmployee.setRowSelectionInterval(0, 0);
     }
    }
   
      String filename = null;
      private ImageIcon viewimage=null;
      private ImageIcon formate=null;
      byte[] employeeimage=null; 
}
