/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.asirisupermarketsystem.panel;

import java.math.BigDecimal;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import lk.ijse.asirisupermarket.controller.ManageEmployeeController;
import lk.ijse.asirisupermarket.core.dto.EmployeeDTO;
import lk.ijse.asirisupermarket.idgenerater.IdGenerater;
import lk.ijse.asirisupermarket.util.Validation;

/**
 *
 * @author Hafees
 */
public class ManageEmployee extends javax.swing.JPanel {
    //String filename = null;
   // private ImageIcon viewimage=null;
   // private ImageIcon formate=null;
    private String gender;
    //byte[] employeeimage=null;
    private  String strgender;
    /**
     * Creates new form AddUser
     */
    public ManageEmployee() {
        initComponents();
          loadAllEmployees();
          setId();
          //loadSystemDate();
          //rowSelection();
          //tblEmployee.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
          //tblEmployee.setRowSelectionInterval(0, 0);
          //tblEmployee.setSelectionModel(new ForcedListSelectionModel());
         // jRadioButton1.setSelected(false);
       // jRadioButton1.setVisible(false);
         // btn_save.setEnabled(false);
          
          tblEmployee.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
               
                //btn_update.setEnabled(true);
               // btn_delete.setEnabled(true);
                 if (tblEmployee.getSelectedRow() == -1) return;
                 
                String employeeId= tblEmployee.getValueAt(tblEmployee.getSelectedRow(), 0).toString();
                String employeefName= tblEmployee.getValueAt(tblEmployee.getSelectedRow(), 1).toString();
                String employeeLName= tblEmployee.getValueAt(tblEmployee.getSelectedRow(), 2).toString();
                String employeeGender= tblEmployee.getValueAt(tblEmployee.getSelectedRow(), 3).toString();
                String employeeDob= tblEmployee.getValueAt(tblEmployee.getSelectedRow(), 4).toString();
                String employeeAddtress= tblEmployee.getValueAt(tblEmployee.getSelectedRow(), 5).toString();
                String employeeSalary= tblEmployee.getValueAt(tblEmployee.getSelectedRow(), 6).toString();
                String employeeContactno= tblEmployee.getValueAt(tblEmployee.getSelectedRow(), 7).toString();
                String employeeEmail= tblEmployee.getValueAt(tblEmployee.getSelectedRow(), 8).toString();
                String employeePosition= tblEmployee.getValueAt(tblEmployee.getSelectedRow(), 9).toString();
                //Byte[] imagedata =tblEmployee.getValueAt(tblEmployee.getSelectedRow(), 10).toByteArray();
                
                txtid.setText(employeeId);
                txtFname.setText(employeefName);
                txtLastname.setText(employeeLName);
                /* if("Male".equals(strgender)){
         jRadioButton_Male.setSelected(true);
         }
                 if("Female".equals(strgender)){
         jRadioButton_Female.setSelected(true);
         
         }*/
                
                txtGender.setText(employeeGender);
                txtDob.setText(employeeDob);
                txtAddress.setText(employeeAddtress);
                txtSalary.setText(employeeSalary);
                txtContact.setText(employeeContactno);
                txtEmail.setText(employeeEmail);
                txtPosition.setText(employeePosition);
                //txtImagepath.setText(employeeSalary);
                
            }
        });
          
          
    }
      public void setId() {
        try {
            String newId = IdGenerater.getNewId("Employee", "EID", "E", 2);
            txtid.setText(newId);
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        id_lbl = new javax.swing.JLabel();
        email_lbl = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtFname = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        mobilphn_lbl1 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        name_lbl1 = new javax.swing.JLabel();
        gender_lbl = new javax.swing.JLabel();
        email_lbl2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        name_lbl2 = new javax.swing.JLabel();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        name_lbl3 = new javax.swing.JLabel();
        txtLastname = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        name_lbl4 = new javax.swing.JLabel();
        txtDob = new javax.swing.JTextField();
        name_lbl5 = new javax.swing.JLabel();
        mobilphn_lbl2 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        txtPosition = new javax.swing.JTextField();
        email_lbl6 = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btn_new = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        TxtSearch = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btn_print = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton_Female = new javax.swing.JRadioButton();
        jRadioButton_Male = new javax.swing.JRadioButton();
        btnSearch = new javax.swing.JToggleButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1097, 629));
        setMinimumSize(new java.awt.Dimension(1097, 629));
        setPreferredSize(new java.awt.Dimension(1144, 629));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Employee");

        id_lbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        id_lbl.setForeground(new java.awt.Color(0, 0, 204));
        id_lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        id_lbl.setText("ID :");

        email_lbl.setBackground(new java.awt.Color(255, 255, 255));
        email_lbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        email_lbl.setForeground(new java.awt.Color(0, 0, 204));
        email_lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        email_lbl.setText("Email ID :");

        txtid.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtid.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 3, true));

        txtFname.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtFname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 3, true));
        txtFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFnameActionPerformed(evt);
            }
        });
        txtFname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFnameKeyReleased(evt);
            }
        });

        txtEmail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 3, true));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        mobilphn_lbl1.setBackground(new java.awt.Color(255, 255, 255));
        mobilphn_lbl1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        mobilphn_lbl1.setForeground(new java.awt.Color(0, 0, 204));
        mobilphn_lbl1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mobilphn_lbl1.setText("Mobile Phone :");

        txtAddress.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtAddress.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 3, true));
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        name_lbl1.setBackground(new java.awt.Color(255, 255, 255));
        name_lbl1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        name_lbl1.setForeground(new java.awt.Color(0, 0, 204));
        name_lbl1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name_lbl1.setText("Employee First Name");

        gender_lbl.setBackground(new java.awt.Color(255, 255, 255));
        gender_lbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        gender_lbl.setForeground(new java.awt.Color(0, 0, 204));
        gender_lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        gender_lbl.setText("Gender:");

        email_lbl2.setBackground(new java.awt.Color(255, 255, 255));
        email_lbl2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        email_lbl2.setForeground(new java.awt.Color(0, 0, 204));
        email_lbl2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        email_lbl2.setText("User Type :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        name_lbl2.setBackground(new java.awt.Color(255, 255, 255));
        name_lbl2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        name_lbl2.setForeground(new java.awt.Color(0, 0, 204));
        name_lbl2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name_lbl2.setText("Address");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "    User Id", "      User Name", "   User Type", "Email Id"
            }
        ));

        tblEmployee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblEmployee.setForeground(new java.awt.Color(255, 0, 255));
        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Id", "User First name", "User Last name", "Gender", "Dob", "Address", "Basic salary", "Contact No", "  Email", "Position", "Image"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Byte.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblEmployee.setGridColor(new java.awt.Color(0, 0, 255));
        tblEmployee.setOpaque(false);
        tblEmployee.setSelectionForeground(new java.awt.Color(51, 255, 51));
        jScrollPane2.setViewportView(tblEmployee);

        name_lbl3.setBackground(new java.awt.Color(255, 255, 255));
        name_lbl3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        name_lbl3.setForeground(new java.awt.Color(0, 0, 204));
        name_lbl3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name_lbl3.setText("Employee Last Name");

        txtLastname.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtLastname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 3, true));
        txtLastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastnameActionPerformed(evt);
            }
        });

        txtGender.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtGender.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 3, true));

        name_lbl4.setBackground(new java.awt.Color(255, 255, 255));
        name_lbl4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        name_lbl4.setForeground(new java.awt.Color(0, 0, 204));
        name_lbl4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name_lbl4.setText("Gender");

        txtDob.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtDob.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 3, true));

        name_lbl5.setBackground(new java.awt.Color(255, 255, 255));
        name_lbl5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        name_lbl5.setForeground(new java.awt.Color(0, 0, 204));
        name_lbl5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name_lbl5.setText("DOB");

        mobilphn_lbl2.setBackground(new java.awt.Color(255, 255, 255));
        mobilphn_lbl2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        mobilphn_lbl2.setForeground(new java.awt.Color(0, 0, 204));
        mobilphn_lbl2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mobilphn_lbl2.setText("Salary");

        txtContact.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtContact.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 3, true));
        txtContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactActionPerformed(evt);
            }
        });

        txtPosition.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtPosition.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 3, true));

        email_lbl6.setBackground(new java.awt.Color(255, 255, 255));
        email_lbl6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        email_lbl6.setForeground(new java.awt.Color(0, 0, 204));
        email_lbl6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        email_lbl6.setText("Position");

        txtSalary.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtSalary.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 3, true));
        txtSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalaryActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_new.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_new.setText("New");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        btn_save.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_update.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        TxtSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("SEARCH");

        btn_print.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_print.setText("Print");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_new)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_update)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_clear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_print, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addComponent(btn_save, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_update, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_new, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_clear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );

        jRadioButton1.setText("r3");

        jRadioButton_Female.setText("Female");
        jRadioButton_Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_FemaleActionPerformed(evt);
            }
        });

        jRadioButton_Male.setText("Male");
        jRadioButton_Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_MaleActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(id_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(name_lbl1)
                            .addComponent(name_lbl3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(name_lbl4)))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(mobilphn_lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(mobilphn_lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email_lbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(gender_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(email_lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButton_Male)
                                                .addGap(23, 23, 23)
                                                .addComponent(jRadioButton_Female)
                                                .addGap(21, 21, 21)
                                                .addComponent(jRadioButton1))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(name_lbl5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(name_lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15554, 15554, 15554)
                        .addComponent(jTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(id_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(name_lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(name_lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(name_lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(mobilphn_lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(mobilphn_lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(email_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(email_lbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSearch))
                                .addGap(17, 17, 17)
                                .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gender_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton_Male)
                    .addComponent(jRadioButton_Female)
                    .addComponent(jRadioButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(name_lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(email_lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name_lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jTable1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
     
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jRadioButton_FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_FemaleActionPerformed
        gender="Female";
    }//GEN-LAST:event_jRadioButton_FemaleActionPerformed

    private void jRadioButton_MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_MaleActionPerformed
        gender="Male" ;
    }//GEN-LAST:event_jRadioButton_MaleActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
//        EmployeeDTO employee = new EmployeeDTO();             
//        txtid.getText(),
//                txtFname.getText(),
//                txtLastname.getText(),
//                txtGender.getText(),
//                parseDate(txtDob.getText()),
//                txtAddress.getText(),
//                new BigDecimal(txtSalary.getText()),
//                txtContact.getText(),
//                txtEmail.getText(),
//                txtPosition.getText();
//                //employeeimage);
//         try {
//            
//            boolean result = ManageEmployeeController.employeeDAO.add(employee);
//            if (result){
//                JOptionPane.showMessageDialog(this, "Employee has been successfully added.");
//                loadAllEmployees(); 
//                 clearAllTextFileds();
//                  setId();
//                 btn_save.setEnabled(false);
//                btn_new.setEnabled(true);
//                btn_update.setEnabled(true);
//                btn_delete.setEnabled(true);
//                btn_clear.setEnabled(true);
//            }else{
//                JOptionPane.showMessageDialog(this, "Employee hasn't been added ");
//            }
//            
//        } catch (Exception ex) {
//            Logger.getLogger(ManageEmployee.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
         clearAllTextFileds();
        btn_save.setEnabled(true);
        btn_new.setEnabled(false);
        btn_update.setEnabled(false);
        btn_delete.setEnabled(false);
        btn_clear.setEnabled(false);
    }//GEN-LAST:event_btn_newActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
       clearAllTextFileds();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
//       EmployeeDTO employee = new EmployeeDTO(
//		txtid.getText(),
//                txtFname.getText(),
//                txtLastname.getText(),
//                txtGender.getText(),
//                //parseDate(txtDob.getText()),
//                txtAddress.getText(),
//                new BigDecimal(txtSalary.getText()),
//                txtContact.getText(),
//                txtEmail.getText(),
//                txtPosition.getText());
//               // employeeimage);
//        try {
//           
//            boolean result = ManageEmployeeController.employeeDAO.delete(employee);
//            if (result){
//                JOptionPane.showMessageDialog(this, "Employee has been successfully deleted.");
//                loadAllEmployees(); 
//                 clearAllTextFileds();
//            }else{
//                JOptionPane.showMessageDialog(this, "Employee hasn't been deleted ");
//            }
//            
//        } catch (Exception ex) {
//            Logger.getLogger(ManageEmployee.class.getName()).log(Level.SEVERE, null, ex);
//        }        
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
//         EmployeeDTO employee = new EmployeeDTO(
//		txtid.getText(),
//                txtFname.getText(),
//                txtLastname.getText(),
//                txtGender.getText(),
//                parseDate(txtDob.getText()),
//                txtAddress.getText(),
//                new BigDecimal(txtSalary.getText()),
//                txtContact.getText(),
//                txtEmail.getText(),
//                txtPosition.getText());
//                //employeeimage);
//        try {
//           
//            boolean result = ManageEmployeeController.employeeDAO.update(employee);
//            if (result){
//                JOptionPane.showMessageDialog(this, "Employee has been successfully updated");
//                loadAllEmployees(); 
//                 clearAllTextFileds();
//            }else{
//                JOptionPane.showMessageDialog(this, "Employee hasn't been updated");
//            }
//            
//        } catch (Exception ex) {
//            Logger.getLogger(ManageEmployee.class.getName()).log(Level.SEVERE, null, ex);
//        }        
        
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
       tblEmployee.setRowSelectionAllowed(true);
    }//GEN-LAST:event_btn_printActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
       String EID = txtid.getText();
        try {
            searchEmployee(EID);
        } catch (Exception ex) {
            Logger.getLogger(ManageEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFnameActionPerformed
        txtLastname.requestFocus();
    }//GEN-LAST:event_txtFnameActionPerformed

    private void txtLastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastnameActionPerformed
        txtGender.requestFocus();
    }//GEN-LAST:event_txtLastnameActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
       txtSalary.requestFocus();
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactActionPerformed
      txtEmail.requestFocus();
    }//GEN-LAST:event_txtContactActionPerformed

    private void txtSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalaryActionPerformed
        txtContact.requestFocus();
    }//GEN-LAST:event_txtSalaryActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
       txtPosition.requestFocus();
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtFnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFnameKeyReleased
         Validation.name(txtFname);
    }//GEN-LAST:event_txtFnameKeyReleased
   /* private void btn_imageuploadActionPerformed(java.awt.event.ActionEvent evt) {                                                
      
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename=f.getAbsolutePath();
        txtImagepath.setText(filename);
        
        try {
            
            File image =new File(filename);
            
            BufferedImage thumbanail = Thumbnails.of(image).size(220, 230).asBufferedImage();
            
            ByteArrayOutputStream os = new ByteArrayOutputStream();
            
            ImageIO.write(thumbanail, "jpeg", os);
            
            InputStream is = new ByteArrayInputStream(os.toByteArray());
            
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            
            byte[] buf = new byte[1024];  // 1 MB
            
            for(int readNum;(readNum = is.read(buf))!=-1;){
            
            bos.write(buf,0,readNum);
            
            
            }
            
            viewimage=new ImageIcon(thumbanail);
            lblImage.setIcon(viewimage);
            
            
            employeeimage=bos.toByteArray();
            
           
             
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
        
        
    }  */
    
     public void searchEmployee(String EID) throws Exception {
       EmployeeDTO employeedto = ManageEmployeeController.employeeDAO.search(EID);
       
       //EmployeeDTO employeedto=ManageEmployeeController.searchEmployee(employeedto);
        if (employeedto != null) {
            
                txtFname.setText(employeedto.getEmployee_FirstName());
                txtLastname.setText(employeedto.getEmployee_LastName());
                txtGender.setText(employeedto.getEmployee_Gender());
                //Date date = new Date();
                //SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
                //txtDob.setText(dateFormat.format(date));
              // parseDate(txtDob.setText(employeedto.getDate_Of_Birth()));
                txtAddress.setText(employeedto.getEmployee_Address());
                txtSalary.setText(employeedto.getBasic_Salary().toPlainString());
                txtContact.setText(employeedto.getContact_No());
                txtEmail.setText(employeedto.getEmployee_Email());
                txtPosition.setText(employeedto.getPosition());
        }
        

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtSearch;
    private javax.swing.JToggleButton btnSearch;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel email_lbl;
    private javax.swing.JLabel email_lbl2;
    private javax.swing.JLabel email_lbl6;
    private javax.swing.JLabel gender_lbl;
    private javax.swing.JLabel id_lbl;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton_Female;
    private javax.swing.JRadioButton jRadioButton_Male;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel mobilphn_lbl1;
    private javax.swing.JLabel mobilphn_lbl2;
    private javax.swing.JLabel name_lbl1;
    private javax.swing.JLabel name_lbl2;
    private javax.swing.JLabel name_lbl3;
    private javax.swing.JLabel name_lbl4;
    private javax.swing.JLabel name_lbl5;
    private javax.swing.JTable tblEmployee;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables

    private void loadAllEmployees() {
        try {
           
           ArrayList<EmployeeDTO> allEmployees = ManageEmployeeController.employeeDAO.getAll();
            
            DefaultTableModel dtm = (DefaultTableModel) tblEmployee.getModel();
            
            dtm.setRowCount(0);
            
            if (allEmployees != null){
                
                for (EmployeeDTO employee : allEmployees) {
                    
                    Object[] rowData = {
                        employee.getEID(),
                        employee.getEmployee_FirstName(),
                        employee.getEmployee_LastName(),
                        employee.getEmployee_Gender(),
                        employee.getDate_Of_Birth(),
                        employee.getEmployee_Address(),
                        employee.getBasic_Salary(),
                        employee.getContact_No(),
                        employee.getEmployee_Email(),
                        employee.getPosition(),
                        
                        //employee.getSalary().toString()
                    };
                    
                    dtm.addRow(rowData);
                    
                }
                
            }
            
        } catch (Exception ex) {
            Logger.getLogger(ManageEmployee     .class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     private Date parseDate(String date){
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        try {
            return sdf.parse(date);
        } catch (ParseException ex) {
            Logger.getLogger(ManageEmployee.class.getName()).log(Level.SEVERE, null, ex);
            return null;            
        }
    }
      
     
     private void loadSystemDate() {
        Date d1 = new Date(); //Current System date
        SimpleDateFormat df = new SimpleDateFormat("YYYY-MM-dd");
        String formatDate = df.format(d1);
        txtDob.setText(formatDate);

    }
   
                         

    private void clearAllTextFileds() {
                 txtid.setText("");
                txtFname.setText("");
                txtLastname.setText("");
                txtGender.setText("");
                txtDob.setText("");
                txtAddress.setText("");
                txtSalary.setText("");
                txtContact.setText("");
                txtEmail.setText("");
                txtPosition.setText("");
                //lblImage.setIcon(null);
                //txtImagepath.setText("");
                
                // jRadioButton_Male.setSelected(false);
                 //jRadioButton_Female.setSelected(false);
                // jRadioButton1.setSelected(true);
    }
    private void rowSelection(){
     int raw=tblEmployee.getSelectedRow();
     if(raw> -1){
     tblEmployee.setRowSelectionInterval(0, 0);
     }
    }
    /*public class ForcedListSelectionModel extends DefaultListSelectionModel {

    public ForcedListSelectionModel () {
        setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    @Override
    public void clearSelection() {
    }

    @Override
    public void removeSelectionInterval(int index0, int index1) {
    }

}*/
   
}
