/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.asirisupermarketsystem.panel;

/**
 *
 * @author Hafees
 */
//@Report("lk.ijse.asirisupermarket.report")
public class ManageReport extends javax.swing.JPanel {

    /**
     * Creates new form ManageReport
     */
    public ManageReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jToggleButton16 = new javax.swing.JToggleButton();
        jToggleButton20 = new javax.swing.JToggleButton();
        jXDatePicker4 = new org.jdesktop.swingx.JXDatePicker();
        txtdate3 = new org.jdesktop.swingx.JXDatePicker();
        btnshowreport6 = new javax.swing.JToggleButton();
        btnshowreport7 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        jToggleButton19 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1352, 475));
        jPanel1.setMinimumSize(new java.awt.Dimension(1352, 475));
        jPanel1.setPreferredSize(new java.awt.Dimension(1352, 475));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 255, 102));
        jLabel7.setText("Select Date");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 255, 102));
        jLabel8.setText("Daily Payment Detail ");

        jToggleButton16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jToggleButton16.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton16.setText("7.Fast Seller Products");
        jToggleButton16.setBorder(null);
        jToggleButton16.setBorderPainted(false);
        jToggleButton16.setContentAreaFilled(false);
        jToggleButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });

        jToggleButton20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jToggleButton20.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton20.setText("6.Invoice more than 3 items");
        jToggleButton20.setBorder(null);
        jToggleButton20.setBorderPainted(false);
        jToggleButton20.setContentAreaFilled(false);
        jToggleButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });

        btnshowreport6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnshowreport6.setForeground(new java.awt.Color(255, 255, 255));
        btnshowreport6.setText("1.Show report");
        btnshowreport6.setBorderPainted(false);
        btnshowreport6.setContentAreaFilled(false);
        btnshowreport6.setFocusPainted(false);
        btnshowreport6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowreportActionPerformed(evt);
            }
        });

        btnshowreport7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnshowreport7.setForeground(new java.awt.Color(255, 255, 255));
        btnshowreport7.setText("2.Show report");
        btnshowreport7.setBorderPainted(false);
        btnshowreport7.setContentAreaFilled(false);
        btnshowreport7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowreport1ActionPerformed(evt);
            }
        });

        jToggleButton18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jToggleButton18.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton18.setText("4.Invoice Amount");
        jToggleButton18.setBorder(null);
        jToggleButton18.setBorderPainted(false);
        jToggleButton18.setContentAreaFilled(false);
        jToggleButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        jToggleButton19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jToggleButton19.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton19.setText("5.Product Report");
        jToggleButton19.setBorder(null);
        jToggleButton19.setBorderPainted(false);
        jToggleButton19.setContentAreaFilled(false);
        jToggleButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jToggleButton17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jToggleButton17.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton17.setText("3.Order Report");
        jToggleButton17.setBorder(null);
        jToggleButton17.setBorderPainted(false);
        jToggleButton17.setContentAreaFilled(false);
        jToggleButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Reports");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 255, 102));
        jLabel10.setText("Daily Order Detail ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 255, 102));
        jLabel11.setText("Select Date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(btnshowreport6)
                .addGap(30, 30, 30)
                .addComponent(txtdate3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jToggleButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(btnshowreport7)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jXDatePicker4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jToggleButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jToggleButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(407, 407, 407)
                .addComponent(jToggleButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jToggleButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnshowreport6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdate3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnshowreport7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jXDatePicker4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToggleButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jToggleButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToggleButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jToggleButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
//        JasperUtil.init(ManageReport.class);
//
//        JasperReportsContext ctx = JasperUtil.getReportContext();
//
//        try {
//            JasperReport compiledReport = JasperUtil.
//            getCompiledReport("qty by invoice.jasper");
//
//            JasperFillManager fillManager = JasperFillManager.getInstance(ctx);
//
//            HashMap<String, Object> reportParams = new HashMap<>();
//
//            // TableModel model = tblorder.getModel();
//            Connection connection = DBConnection.getInstance().getConnection();
//
//            JasperPrint filledReport = fillManager.
//            fill(compiledReport, reportParams,connection );
//
//            IJSEJasperViewer frmJasperViewer = new IJSEJasperViewer(filledReport);
//            frmJasperViewer.setTitle("INVOICE AMOUNT  Report");
//            frmJasperViewer.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
//            frmJasperViewer.setVisible(true);
//
//        } catch (JRException ex) {
//            Logger.getLogger(ManageReport.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
//        JasperUtil.init(ManageReport.class);
//
//        JasperReportsContext ctx = JasperUtil.getReportContext();
//
//        try {
//            JasperReport compiledReport = JasperUtil.
//            getCompiledReport("Product detail.jasper");
//
//            JasperFillManager fillManager = JasperFillManager.getInstance(ctx);
//
//            HashMap<String, Object> reportParams = new HashMap<>();
//
//            // TableModel model = tblorder.getModel();
//            Connection connection = DBConnection.getInstance().getConnection();
//
//            JasperPrint filledReport = fillManager.
//            fill(compiledReport, reportParams,connection );
//
//            IJSEJasperViewer frmJasperViewer = new IJSEJasperViewer(filledReport);
//            frmJasperViewer.setTitle("Product  Report");
//            frmJasperViewer.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
//            frmJasperViewer.setVisible(true);
//
//        } catch (JRException ex) {
//            Logger.getLogger(ManageReport.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
//        JasperUtil.init(ManageReport.class);
//
//        JasperReportsContext ctx = JasperUtil.getReportContext();
//
//        try {
//            JasperReport compiledReport = JasperUtil.
//            getCompiledReport("INVOICE AMOUNT DETAILS.jasper");
//
//            JasperFillManager fillManager = JasperFillManager.getInstance(ctx);
//
//            HashMap<String, Object> reportParams = new HashMap<>();
//
//            // TableModel model = tblorder.getModel();
//            Connection connection = DBConnection.getInstance().getConnection();
//
//            JasperPrint filledReport = fillManager.
//            fill(compiledReport, reportParams,connection );
//
//            IJSEJasperViewer frmJasperViewer = new IJSEJasperViewer(filledReport);
//            frmJasperViewer.setTitle("INVOICE AMOUNT  Report");
//            frmJasperViewer.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
//            frmJasperViewer.setVisible(true);
//
//        } catch (JRException ex) {
//            Logger.getLogger(ManageReport.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
//        JasperUtil.init(ManageReport.class);
//
//        JasperReportsContext ctx = JasperUtil.getReportContext();
//
//        try {
//            JasperReport compiledReport = JasperUtil.
//            getCompiledReport("order11.jasper");
//
//            JasperFillManager fillManager = JasperFillManager.getInstance(ctx);
//
//            HashMap<String, Object> reportParams = new HashMap<>();
//
//            // TableModel model = tblorder.getModel();
//            Connection connection = DBConnection.getInstance().getConnection();
//
//            JasperPrint filledReport = fillManager.
//            fill(compiledReport, reportParams,connection );
//
//            IJSEJasperViewer frmJasperViewer = new IJSEJasperViewer(filledReport);
//            frmJasperViewer.setTitle("Order  Report");
//            frmJasperViewer.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
//            frmJasperViewer.setVisible(true);
//
//        } catch (JRException ex) {
//            Logger.getLogger(ManageReport.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
//        JasperUtil.init(ManageReport.class);
//
//        JasperReportsContext ctx = JasperUtil.getReportContext();
//
//        try {
//            JasperReport compiledReport = JasperUtil.
//            getCompiledReport("fast seller products.jasper");
//
//            JasperFillManager fillManager = JasperFillManager.getInstance(ctx);
//
//            HashMap<String, Object> reportParams = new HashMap<>();
//
//            // TableModel model = tblorder.getModel();
//            Connection connection = DBConnection.getInstance().getConnection();
//
//            JasperPrint filledReport = fillManager.
//            fill(compiledReport, reportParams,connection );
//
//            IJSEJasperViewer frmJasperViewer = new IJSEJasperViewer(filledReport);
//            frmJasperViewer.setTitle("Fast Seller Report");
//            frmJasperViewer.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
//            frmJasperViewer.setVisible(true);
//
//        } catch (JRException ex) {
//            Logger.getLogger(ManageReport.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void btnshowreport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowreport1ActionPerformed
//        JasperUtil.init(ManageReport.class);
//
//        JasperReportsContext ctx = JasperUtil.getReportContext();
//
//        try {
//            JasperReport compiledReport = JasperUtil.
//            getCompiledReport("INVOICE20.jasper");
//
//            JasperFillManager fillManager = JasperFillManager.getInstance(ctx);
//
//            HashMap<String, Object> reportParams = new HashMap<>();
//
//            reportParams.put("date", jXDatePicker1.getDate());
//
//            Connection connection = DBConnection.getInstance().getConnection();
//
//            JasperPrint filledReport = fillManager.
//            fill(compiledReport, reportParams, connection);
//
//            IJSEJasperViewer frmJasperViewer = new IJSEJasperViewer(filledReport);
//            frmJasperViewer.setTitle("Order Details Report");
//            frmJasperViewer.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
//            frmJasperViewer.setVisible(true);
//
//        } catch (JRException ex) {
//            Logger.getLogger(ManageReport.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btnshowreport1ActionPerformed

    private void btnshowreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowreportActionPerformed
//        JasperUtil.init(ManageReport.class);
//
//        JasperReportsContext ctx = JasperUtil.getReportContext();
//
//        try {
//            JasperReport compiledReport = JasperUtil.
//            getCompiledReport("item.jasper");
//
//            JasperFillManager fillManager = JasperFillManager.getInstance(ctx);
//
//            HashMap<String, Object> reportParams = new HashMap<>();
//
//            reportParams.put("date", txtdate.getDate());
//
//            Connection connection = DBConnection.getInstance().getConnection();
//
//            JasperPrint filledReport = fillManager.
//            fill(compiledReport, reportParams, connection);
//
//            IJSEJasperViewer frmJasperViewer = new IJSEJasperViewer(filledReport);
//            frmJasperViewer.setTitle("Order Details Report");
//            frmJasperViewer.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
//            frmJasperViewer.setVisible(true);
//
//        } catch (JRException ex) {
//            Logger.getLogger(ManageReport.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btnshowreportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnshowreport;
    private javax.swing.JToggleButton btnshowreport1;
    private javax.swing.JToggleButton btnshowreport2;
    private javax.swing.JToggleButton btnshowreport3;
    private javax.swing.JToggleButton btnshowreport4;
    private javax.swing.JToggleButton btnshowreport5;
    private javax.swing.JToggleButton btnshowreport6;
    private javax.swing.JToggleButton btnshowreport7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker3;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker4;
    private org.jdesktop.swingx.JXDatePicker txtdate;
    private org.jdesktop.swingx.JXDatePicker txtdate1;
    private org.jdesktop.swingx.JXDatePicker txtdate2;
    private org.jdesktop.swingx.JXDatePicker txtdate3;
    // End of variables declaration//GEN-END:variables
}
