/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.asirisupermarketsystem.panel;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.asirisupermarket.controller.ManagePaymentController;
import lk.ijse.asirisupermarket.core.dto.PaymentDTO;
import lk.ijse.asirisupermarket.idgenerater.IdGenerater;
import lk.ijse.asirisupermarket.subpanels.ManageOrder;
import lk.ijse.asirisupermarket.subpanels.PaymentFinal;

/**
 *
 * @author Hafees
 */
public class ManagePayments extends javax.swing.JPanel {

    /**
     * Creates new form ManageInvoice
     */
    public ManagePayments() {
        initComponents();
       // setInvId();
        loadallpaymentIds();
        loadSystemDate();
       
    }
     public void setInvId() {
        try {
            String newId = IdGenerater.getNewId("Payment", "PID", "INV", 3);
            txtcid.setText(newId);
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtdiscount = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtempid = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtcid = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txttotamount = new javax.swing.JTextField();
        txtoid = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        comboinvid = new javax.swing.JComboBox<>();
        txtinvdate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpayment = new javax.swing.JTable();
        print_btn = new javax.swing.JToggleButton();
        btncancel = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtcurdate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnpayment = new javax.swing.JToggleButton();
        btnviewreport1 = new javax.swing.JToggleButton();

        setMaximumSize(new java.awt.Dimension(1097, 629));
        setMinimumSize(new java.awt.Dimension(1097, 629));

        panel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Order Detail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 204))); // NOI18N

        txtdiscount.setEditable(false);
        txtdiscount.setBackground(new java.awt.Color(255, 255, 255));
        txtdiscount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtdiscount.setForeground(new java.awt.Color(0, 204, 0));
        txtdiscount.setBorder(null);
        txtdiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiscountActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Discount  Rs");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setText("Employee ID");

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel15.setText("Customer Id");

        txtempid.setEditable(false);
        txtempid.setBackground(new java.awt.Color(255, 255, 255));
        txtempid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtempid.setForeground(new java.awt.Color(0, 204, 0));
        txtempid.setBorder(null);
        txtempid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtempidActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel17.setText("OrderId");

        txtcid.setEditable(false);
        txtcid.setBackground(new java.awt.Color(255, 255, 255));
        txtcid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtcid.setForeground(new java.awt.Color(0, 204, 0));
        txtcid.setBorder(null);
        txtcid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcidActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Total  Rs");

        txttotamount.setEditable(false);
        txttotamount.setBackground(new java.awt.Color(255, 255, 255));
        txttotamount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txttotamount.setForeground(new java.awt.Color(0, 204, 0));
        txttotamount.setBorder(null);
        txttotamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotamountActionPerformed(evt);
            }
        });

        txtoid.setEditable(false);
        txtoid.setBackground(new java.awt.Color(255, 255, 255));
        txtoid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtoid.setForeground(new java.awt.Color(0, 204, 0));
        txtoid.setBorder(null);
        txtoid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtoidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel2)
                    .addComponent(jLabel15)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtoid, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(txtcid)
                    .addComponent(txtempid)
                    .addComponent(txtdiscount)
                    .addComponent(txttotamount))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtoid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtempid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttotamount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payment Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("Invoice no");

        jLabel22.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Invoice Date");

        comboinvid.setEditable(true);
        comboinvid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboinvidItemStateChanged(evt);
            }
        });

        txtinvdate.setEditable(false);
        txtinvdate.setBackground(new java.awt.Color(255, 255, 255));
        txtinvdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtinvdate.setForeground(new java.awt.Color(0, 204, 0));
        txtinvdate.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addComponent(jLabel22))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(comboinvid, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtinvdate, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(comboinvid, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtinvdate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tblpayment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 2));
        tblpayment.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblpayment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "       Invoice No", "       Order Date", "          CustomerId", "           Order No", "       Employee ID", "       Discount", "     Total Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblpayment.setToolTipText("Payment Table");
        tblpayment.setGridColor(new java.awt.Color(51, 255, 153));
        tblpayment.setOpaque(false);
        tblpayment.setRowHeight(20);
        tblpayment.setRowMargin(2);
        tblpayment.setSelectionBackground(new java.awt.Color(255, 0, 255));
        tblpayment.setSelectionForeground(new java.awt.Color(0, 0, 255));
        tblpayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpaymentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblpayment);

        print_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        print_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/asirisupermarket/images/Printer-icon.png"))); // NOI18N
        print_btn.setText("Print Invoice");

        btncancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/asirisupermarket/images/Cancel_48px_1.png"))); // NOI18N
        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/asirisupermarket/images/10logos.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 204));
        jLabel13.setText("Payment Details");

        txtcurdate.setEditable(false);
        txtcurdate.setBackground(new java.awt.Color(255, 255, 255));
        txtcurdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtcurdate.setBorder(null);
        txtcurdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcurdateActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Date");

        btnpayment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnpayment.setText("Payment");
        btnpayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpaymentActionPerformed(evt);
            }
        });

        btnviewreport1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnviewreport1.setText("View Report");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(txtcurdate, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)
                        .addComponent(jLabel5))
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panel1Layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(btncancel)
                            .addGap(38, 38, 38)
                            .addComponent(btnviewreport1)
                            .addGap(43, 43, 43)
                            .addComponent(print_btn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnpayment))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtcurdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(print_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpayment, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnviewreport1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtcidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcidActionPerformed

    private void txtempidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtempidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtempidActionPerformed

    private void comboinvidItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboinvidItemStateChanged
        try {
            if(comboinvid.getSelectedIndex()==-1){
                return;
            }
             PaymentDTO payment=ManagePaymentController.paymentDAO.search(new PaymentDTO(comboinvid.getSelectedItem().toString(), null,null,null,null,0.0,0.0));
            if (payment == null) {
                return;
            }

            txtinvdate.setText(payment.getPayment_DATE());
            txtcid.setText(payment.getCID());
            txtempid.setText(payment.getEID());
            txtoid.setText(payment.getOID());
            txtdiscount.setText(payment.getDiscount()+"");
            txttotamount.setText(payment.getTotal_Amount()+"");
        } catch (Exception ex) {
            Logger.getLogger(ManagePayments.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
    }//GEN-LAST:event_comboinvidItemStateChanged

    private void txtdiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdiscountActionPerformed

    private void txtcurdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcurdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcurdateActionPerformed

    private void tblpaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpaymentMouseClicked
       
        if (tblpayment.getSelectedRow()==-1)return;
        
        String pid=tblpayment.getValueAt(tblpayment.getSelectedRow(), 0).toString();
        String orderdate=tblpayment.getValueAt(tblpayment.getSelectedRow(), 1).toString();
        String cid=tblpayment.getValueAt(tblpayment.getSelectedRow(), 2).toString();
        String oid=tblpayment.getValueAt(tblpayment.getSelectedRow(), 3).toString();
        String eid=tblpayment.getValueAt(tblpayment.getSelectedRow(),4).toString();
        String discount=tblpayment.getValueAt(tblpayment.getSelectedRow(), 5).toString();
        String totamount=tblpayment.getValueAt(tblpayment.getSelectedRow(),6).toString();
      
       
        
        comboinvid.setSelectedItem(pid);
        txtinvdate.setText(orderdate);
        txtempid.setText(eid);
        txtdiscount.setText(discount);
        txttotamount.setText(totamount);
        txtoid.setText(oid);
        txtcid.setText(cid);
        
    }//GEN-LAST:event_tblpaymentMouseClicked

    private void txttotamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotamountActionPerformed

    private void txtoidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtoidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtoidActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
         ManageOrder mn=new ManageOrder();
         mn.setSize(panel1.getSize());
         panel1.removeAll();
         panel1.add(mn);
         panel1.repaint();
         panel1.revalidate();
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnpaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpaymentActionPerformed
       PaymentFinal mn=new PaymentFinal();
       mn.setSize(panel1.getSize());
       panel1.removeAll();
       panel1.add(mn);
       panel1.repaint();
       panel1.revalidate();
               
               
    }//GEN-LAST:event_btnpaymentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btncancel;
    private javax.swing.JToggleButton btnpayment;
    private javax.swing.JToggleButton btnviewreport1;
    private javax.swing.JComboBox<String> comboinvid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel1;
    private javax.swing.JToggleButton print_btn;
    private javax.swing.JTable tblpayment;
    private javax.swing.JTextField txtcid;
    private javax.swing.JTextField txtcurdate;
    private javax.swing.JTextField txtdiscount;
    private javax.swing.JTextField txtempid;
    private javax.swing.JTextField txtinvdate;
    private javax.swing.JTextField txtoid;
    private javax.swing.JTextField txttotamount;
    // End of variables declaration//GEN-END:variables

    private void loadallpaymentIds() {
       try {
            ArrayList<PaymentDTO> allPaymentid = ManagePaymentController.paymentDAO.getAll();
           DefaultTableModel dtm=(DefaultTableModel) tblpayment.getModel();
            comboinvid.removeAllItems();
            if (allPaymentid == null) {
                return;
            }

            for (PaymentDTO payment : allPaymentid) {
                comboinvid.addItem(payment.getPID());
            }
            dtm.setRowCount(0);
            if (allPaymentid !=null){
            for(PaymentDTO payment :allPaymentid){
            Object[] rowData={
            payment.getPID(),
            payment.getPayment_DATE(),
            payment.getCID(),
            payment.getOID(),
            payment.getEID(),
            payment.getDiscount(),
            payment.getTotal_Amount()
            };
            dtm.addRow(rowData);
         }
            }
        } catch (Exception ex) {
            Logger.getLogger(ManagePayments.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     private void loadSystemDate() {
        Date d1 = new Date(); //Current System date
        SimpleDateFormat df = new SimpleDateFormat("YYYY-MM-dd");
        String formatDate = df.format(d1);
        txtcurdate.setText(formatDate);

    }

   
    
      
}