/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.asirisupermarketsystem.panel;

import lk.ijse.asirisupermarket.subpanels.ManageBatch;
import lk.ijse.asirisupermarket.subpanels.ManageBrand;
import lk.ijse.asirisupermarket.subpanels.ManageCategory;
import lk.ijse.asirisupermarket.subpanels.ManageGRN;

/**
 *
 * @author Hafees
 */
public class ProductPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel2
     */
    public ProductPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        btnbrand = new javax.swing.JToggleButton();
        btncategory = new javax.swing.JToggleButton();
        btnGRn = new javax.swing.JToggleButton();
        btnOrders = new javax.swing.JToggleButton();
        panel2 = new javax.swing.JPanel();
        btnbrand1 = new javax.swing.JToggleButton();

        panel1.setBackground(new java.awt.Color(0, 0, 255));

        btnbrand.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnbrand.setForeground(new java.awt.Color(0, 51, 255));
        btnbrand.setText("Manage Brand");
        btnbrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbrandActionPerformed(evt);
            }
        });

        btncategory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncategory.setForeground(new java.awt.Color(0, 51, 255));
        btncategory.setText("Manage Category");
        btncategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncategoryActionPerformed(evt);
            }
        });

        btnGRn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGRn.setForeground(new java.awt.Color(0, 51, 255));
        btnGRn.setText("Manage GRN");
        btnGRn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGRnActionPerformed(evt);
            }
        });

        btnOrders.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOrders.setForeground(new java.awt.Color(0, 51, 255));
        btnOrders.setText("Batch");
        btnOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdersActionPerformed(evt);
            }
        });

        panel2.setBackground(new java.awt.Color(0, 0, 255));
        panel2.setForeground(new java.awt.Color(0, 51, 255));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );

        btnbrand1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnbrand1.setForeground(new java.awt.Color(0, 51, 255));
        btnbrand1.setText("Manage Products");
        btnbrand1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbrand1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnbrand1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(btnbrand, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(btncategory)
                .addGap(75, 75, 75)
                .addComponent(btnGRn)
                .addGap(58, 58, 58)
                .addComponent(btnOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addComponent(panel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btncategory, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGRn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnbrand, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnbrand1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnbrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbrandActionPerformed
       //ManageOrder batchpanel=new ManageOrder();
        
       ManageBrand batchpanel = new ManageBrand();
        batchpanel.setSize(panel2.getSize());
        panel2.removeAll();
        panel2.add(batchpanel);
        panel2.repaint();
        panel2.revalidate();
    }//GEN-LAST:event_btnbrandActionPerformed

    private void btncategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncategoryActionPerformed
         ManageCategory mn=new ManageCategory();
        // ordera batchpanel=new ordera();
        mn.setSize(panel2.getSize());
        panel2.removeAll();
        panel2.add(mn);
        panel2.repaint();
        panel2.revalidate();      
    }//GEN-LAST:event_btncategoryActionPerformed

    private void btnGRnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGRnActionPerformed
        ManageGRN mn=new ManageGRN();
        // ordera batchpanel=new ordera();
        mn.setSize(panel2.getSize());
        panel2.removeAll();
        panel2.add(mn);
        panel2.repaint();
        panel2.revalidate();
    }//GEN-LAST:event_btnGRnActionPerformed

    private void btnOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdersActionPerformed
       ManageBatch mn=new ManageBatch();
        // ordera batchpanel=new ordera();
        mn.setSize(panel2.getSize());
        panel2.removeAll();
        panel2.add(mn);
        panel2.repaint();
        panel2.revalidate();
    }//GEN-LAST:event_btnOrdersActionPerformed

    private void btnbrand1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbrand1ActionPerformed
        ManageProducts mn=new ManageProducts();
         mn.setSize(panel2.getSize());
        panel2.removeAll();
        panel2.add(mn);
        panel2.repaint();
        panel2.revalidate();
    }//GEN-LAST:event_btnbrand1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnGRn;
    private javax.swing.JToggleButton btnOrders;
    private javax.swing.JToggleButton btnbrand;
    private javax.swing.JToggleButton btnbrand1;
    private javax.swing.JToggleButton btncategory;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    // End of variables declaration//GEN-END:variables
}
